// Code generated by protoc-gen-go. DO NOT EDIT.
// source: Cloud.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//初始化 laneKey这个值要保证在云路由上唯一
type InitRequest struct {
	LaneKey              string   `protobuf:"bytes,1,opt,name=laneKey,proto3" json:"laneKey,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InitRequest) Reset()         { *m = InitRequest{} }
func (m *InitRequest) String() string { return proto.CompactTextString(m) }
func (*InitRequest) ProtoMessage()    {}
func (*InitRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0bb7cee52a09eea, []int{0}
}

func (m *InitRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InitRequest.Unmarshal(m, b)
}
func (m *InitRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InitRequest.Marshal(b, m, deterministic)
}
func (m *InitRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InitRequest.Merge(m, src)
}
func (m *InitRequest) XXX_Size() int {
	return xxx_messageInfo_InitRequest.Size(m)
}
func (m *InitRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_InitRequest.DiscardUnknown(m)
}

var xxx_messageInfo_InitRequest proto.InternalMessageInfo

func (m *InitRequest) GetLaneKey() string {
	if m != nil {
		return m.LaneKey
	}
	return ""
}

type InitResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InitResponse) Reset()         { *m = InitResponse{} }
func (m *InitResponse) String() string { return proto.CompactTextString(m) }
func (*InitResponse) ProtoMessage()    {}
func (*InitResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0bb7cee52a09eea, []int{1}
}

func (m *InitResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InitResponse.Unmarshal(m, b)
}
func (m *InitResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InitResponse.Marshal(b, m, deterministic)
}
func (m *InitResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InitResponse.Merge(m, src)
}
func (m *InitResponse) XXX_Size() int {
	return xxx_messageInfo_InitResponse.Size(m)
}
func (m *InitResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_InitResponse.DiscardUnknown(m)
}

var xxx_messageInfo_InitResponse proto.InternalMessageInfo

//计费
type FeeRequest struct {
	Vehplate             string   `protobuf:"bytes,1,opt,name=vehplate,proto3" json:"vehplate,omitempty"`
	Vehclass             string   `protobuf:"bytes,2,opt,name=vehclass,proto3" json:"vehclass,omitempty"`
	Entrystaid           string   `protobuf:"bytes,3,opt,name=entrystaid,proto3" json:"entrystaid,omitempty"`
	Exitstaid            string   `protobuf:"bytes,4,opt,name=exitstaid,proto3" json:"exitstaid,omitempty"`
	Flagstaid            string   `protobuf:"bytes,5,opt,name=flagstaid,proto3" json:"flagstaid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FeeRequest) Reset()         { *m = FeeRequest{} }
func (m *FeeRequest) String() string { return proto.CompactTextString(m) }
func (*FeeRequest) ProtoMessage()    {}
func (*FeeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0bb7cee52a09eea, []int{2}
}

func (m *FeeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FeeRequest.Unmarshal(m, b)
}
func (m *FeeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FeeRequest.Marshal(b, m, deterministic)
}
func (m *FeeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FeeRequest.Merge(m, src)
}
func (m *FeeRequest) XXX_Size() int {
	return xxx_messageInfo_FeeRequest.Size(m)
}
func (m *FeeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FeeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FeeRequest proto.InternalMessageInfo

func (m *FeeRequest) GetVehplate() string {
	if m != nil {
		return m.Vehplate
	}
	return ""
}

func (m *FeeRequest) GetVehclass() string {
	if m != nil {
		return m.Vehclass
	}
	return ""
}

func (m *FeeRequest) GetEntrystaid() string {
	if m != nil {
		return m.Entrystaid
	}
	return ""
}

func (m *FeeRequest) GetExitstaid() string {
	if m != nil {
		return m.Exitstaid
	}
	return ""
}

func (m *FeeRequest) GetFlagstaid() string {
	if m != nil {
		return m.Flagstaid
	}
	return ""
}

type FeeResponse struct {
	Toll                 string   `protobuf:"bytes,1,opt,name=toll,proto3" json:"toll,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FeeResponse) Reset()         { *m = FeeResponse{} }
func (m *FeeResponse) String() string { return proto.CompactTextString(m) }
func (*FeeResponse) ProtoMessage()    {}
func (*FeeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0bb7cee52a09eea, []int{3}
}

func (m *FeeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FeeResponse.Unmarshal(m, b)
}
func (m *FeeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FeeResponse.Marshal(b, m, deterministic)
}
func (m *FeeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FeeResponse.Merge(m, src)
}
func (m *FeeResponse) XXX_Size() int {
	return xxx_messageInfo_FeeResponse.Size(m)
}
func (m *FeeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FeeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FeeResponse proto.InternalMessageInfo

func (m *FeeResponse) GetToll() string {
	if m != nil {
		return m.Toll
	}
	return ""
}

//车牌付校验
type PlatePayCheckRequest struct {
	Vehplate             string   `protobuf:"bytes,1,opt,name=Vehplate,proto3" json:"Vehplate,omitempty"`
	Vehclass             string   `protobuf:"bytes,2,opt,name=Vehclass,proto3" json:"Vehclass,omitempty"`
	TID                  string   `protobuf:"bytes,3,opt,name=TID,proto3" json:"TID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PlatePayCheckRequest) Reset()         { *m = PlatePayCheckRequest{} }
func (m *PlatePayCheckRequest) String() string { return proto.CompactTextString(m) }
func (*PlatePayCheckRequest) ProtoMessage()    {}
func (*PlatePayCheckRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0bb7cee52a09eea, []int{4}
}

func (m *PlatePayCheckRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlatePayCheckRequest.Unmarshal(m, b)
}
func (m *PlatePayCheckRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlatePayCheckRequest.Marshal(b, m, deterministic)
}
func (m *PlatePayCheckRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlatePayCheckRequest.Merge(m, src)
}
func (m *PlatePayCheckRequest) XXX_Size() int {
	return xxx_messageInfo_PlatePayCheckRequest.Size(m)
}
func (m *PlatePayCheckRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PlatePayCheckRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PlatePayCheckRequest proto.InternalMessageInfo

func (m *PlatePayCheckRequest) GetVehplate() string {
	if m != nil {
		return m.Vehplate
	}
	return ""
}

func (m *PlatePayCheckRequest) GetVehclass() string {
	if m != nil {
		return m.Vehclass
	}
	return ""
}

func (m *PlatePayCheckRequest) GetTID() string {
	if m != nil {
		return m.TID
	}
	return ""
}

type PlatePayCheckResponse struct {
	CheckResult          string   `protobuf:"bytes,1,opt,name=CheckResult,proto3" json:"CheckResult,omitempty"`
	Vehplate             string   `protobuf:"bytes,2,opt,name=Vehplate,proto3" json:"Vehplate,omitempty"`
	Vehclass             string   `protobuf:"bytes,3,opt,name=Vehclass,proto3" json:"Vehclass,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PlatePayCheckResponse) Reset()         { *m = PlatePayCheckResponse{} }
func (m *PlatePayCheckResponse) String() string { return proto.CompactTextString(m) }
func (*PlatePayCheckResponse) ProtoMessage()    {}
func (*PlatePayCheckResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0bb7cee52a09eea, []int{5}
}

func (m *PlatePayCheckResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlatePayCheckResponse.Unmarshal(m, b)
}
func (m *PlatePayCheckResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlatePayCheckResponse.Marshal(b, m, deterministic)
}
func (m *PlatePayCheckResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlatePayCheckResponse.Merge(m, src)
}
func (m *PlatePayCheckResponse) XXX_Size() int {
	return xxx_messageInfo_PlatePayCheckResponse.Size(m)
}
func (m *PlatePayCheckResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PlatePayCheckResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PlatePayCheckResponse proto.InternalMessageInfo

func (m *PlatePayCheckResponse) GetCheckResult() string {
	if m != nil {
		return m.CheckResult
	}
	return ""
}

func (m *PlatePayCheckResponse) GetVehplate() string {
	if m != nil {
		return m.Vehplate
	}
	return ""
}

func (m *PlatePayCheckResponse) GetVehclass() string {
	if m != nil {
		return m.Vehclass
	}
	return ""
}

//请求支付
type PayRequest struct {
	Operatorid           string   `protobuf:"bytes,1,opt,name=Operatorid,proto3" json:"Operatorid,omitempty"`
	Shiftid              string   `protobuf:"bytes,2,opt,name=Shiftid,proto3" json:"Shiftid,omitempty"`
	TransDate            string   `protobuf:"bytes,3,opt,name=TransDate,proto3" json:"TransDate,omitempty"`
	Paytype              string   `protobuf:"bytes,4,opt,name=Paytype,proto3" json:"Paytype,omitempty"`
	PayCode              string   `protobuf:"bytes,5,opt,name=PayCode,proto3" json:"PayCode,omitempty"`
	Vehplate             string   `protobuf:"bytes,6,opt,name=Vehplate,proto3" json:"Vehplate,omitempty"`
	Toll                 string   `protobuf:"bytes,7,opt,name=Toll,proto3" json:"Toll,omitempty"`
	Transtime            string   `protobuf:"bytes,8,opt,name=Transtime,proto3" json:"Transtime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PayRequest) Reset()         { *m = PayRequest{} }
func (m *PayRequest) String() string { return proto.CompactTextString(m) }
func (*PayRequest) ProtoMessage()    {}
func (*PayRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0bb7cee52a09eea, []int{6}
}

func (m *PayRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PayRequest.Unmarshal(m, b)
}
func (m *PayRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PayRequest.Marshal(b, m, deterministic)
}
func (m *PayRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PayRequest.Merge(m, src)
}
func (m *PayRequest) XXX_Size() int {
	return xxx_messageInfo_PayRequest.Size(m)
}
func (m *PayRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PayRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PayRequest proto.InternalMessageInfo

func (m *PayRequest) GetOperatorid() string {
	if m != nil {
		return m.Operatorid
	}
	return ""
}

func (m *PayRequest) GetShiftid() string {
	if m != nil {
		return m.Shiftid
	}
	return ""
}

func (m *PayRequest) GetTransDate() string {
	if m != nil {
		return m.TransDate
	}
	return ""
}

func (m *PayRequest) GetPaytype() string {
	if m != nil {
		return m.Paytype
	}
	return ""
}

func (m *PayRequest) GetPayCode() string {
	if m != nil {
		return m.PayCode
	}
	return ""
}

func (m *PayRequest) GetVehplate() string {
	if m != nil {
		return m.Vehplate
	}
	return ""
}

func (m *PayRequest) GetToll() string {
	if m != nil {
		return m.Toll
	}
	return ""
}

func (m *PayRequest) GetTranstime() string {
	if m != nil {
		return m.Transtime
	}
	return ""
}

//支付应答结果
type PayResponse struct {
	Paytype              string   `protobuf:"bytes,1,opt,name=Paytype,proto3" json:"Paytype,omitempty"`
	Paymethod            string   `protobuf:"bytes,2,opt,name=Paymethod,proto3" json:"Paymethod,omitempty"`
	Goodsno              string   `protobuf:"bytes,3,opt,name=Goodsno,proto3" json:"Goodsno,omitempty"`
	Tradeno              string   `protobuf:"bytes,4,opt,name=Tradeno,proto3" json:"Tradeno,omitempty"`
	Toll                 string   `protobuf:"bytes,5,opt,name=Toll,proto3" json:"Toll,omitempty"`
	Paytime              string   `protobuf:"bytes,6,opt,name=Paytime,proto3" json:"Paytime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PayResponse) Reset()         { *m = PayResponse{} }
func (m *PayResponse) String() string { return proto.CompactTextString(m) }
func (*PayResponse) ProtoMessage()    {}
func (*PayResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0bb7cee52a09eea, []int{7}
}

func (m *PayResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PayResponse.Unmarshal(m, b)
}
func (m *PayResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PayResponse.Marshal(b, m, deterministic)
}
func (m *PayResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PayResponse.Merge(m, src)
}
func (m *PayResponse) XXX_Size() int {
	return xxx_messageInfo_PayResponse.Size(m)
}
func (m *PayResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PayResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PayResponse proto.InternalMessageInfo

func (m *PayResponse) GetPaytype() string {
	if m != nil {
		return m.Paytype
	}
	return ""
}

func (m *PayResponse) GetPaymethod() string {
	if m != nil {
		return m.Paymethod
	}
	return ""
}

func (m *PayResponse) GetGoodsno() string {
	if m != nil {
		return m.Goodsno
	}
	return ""
}

func (m *PayResponse) GetTradeno() string {
	if m != nil {
		return m.Tradeno
	}
	return ""
}

func (m *PayResponse) GetToll() string {
	if m != nil {
		return m.Toll
	}
	return ""
}

func (m *PayResponse) GetPaytime() string {
	if m != nil {
		return m.Paytime
	}
	return ""
}

//出口交易数据
type ExitFlowRequest struct {
	Vehclass             string   `protobuf:"bytes,1,opt,name=Vehclass,proto3" json:"Vehclass,omitempty"`
	Vehplate             string   `protobuf:"bytes,2,opt,name=Vehplate,proto3" json:"Vehplate,omitempty"`
	ExitNetwork          string   `protobuf:"bytes,3,opt,name=ExitNetwork,proto3" json:"ExitNetwork,omitempty"`
	ExitStationid        string   `protobuf:"bytes,4,opt,name=ExitStationid,proto3" json:"ExitStationid,omitempty"`
	ExitLandid           string   `protobuf:"bytes,5,opt,name=ExitLandid,proto3" json:"ExitLandid,omitempty"`
	ExitOperator         string   `protobuf:"bytes,6,opt,name=ExitOperator,proto3" json:"ExitOperator,omitempty"`
	ExitShiftdate        string   `protobuf:"bytes,7,opt,name=ExitShiftdate,proto3" json:"ExitShiftdate,omitempty"`
	ExitShift            string   `protobuf:"bytes,8,opt,name=ExitShift,proto3" json:"ExitShift,omitempty"`
	Paytype              string   `protobuf:"bytes,9,opt,name=Paytype,proto3" json:"Paytype,omitempty"`
	Paymethod            string   `protobuf:"bytes,10,opt,name=Paymethod,proto3" json:"Paymethod,omitempty"`
	Payid                string   `protobuf:"bytes,11,opt,name=Payid,proto3" json:"Payid,omitempty"`
	Transtime            string   `protobuf:"bytes,12,opt,name=Transtime,proto3" json:"Transtime,omitempty"`
	Paytime              string   `protobuf:"bytes,13,opt,name=Paytime,proto3" json:"Paytime,omitempty"`
	Toll                 string   `protobuf:"bytes,14,opt,name=Toll,proto3" json:"Toll,omitempty"`
	Goodsno              string   `protobuf:"bytes,15,opt,name=Goodsno,proto3" json:"Goodsno,omitempty"`
	Tradeno              string   `protobuf:"bytes,16,opt,name=Tradeno,proto3" json:"Tradeno,omitempty"`
	PrintFlag            string   `protobuf:"bytes,17,opt,name=PrintFlag,proto3" json:"PrintFlag,omitempty"`
	Termid               string   `protobuf:"bytes,18,opt,name=Termid,proto3" json:"Termid,omitempty"`
	Termno               string   `protobuf:"bytes,19,opt,name=Termno,proto3" json:"Termno,omitempty"`
	Tac                  string   `protobuf:"bytes,20,opt,name=Tac,proto3" json:"Tac,omitempty"`
	CardTradeNo          string   `protobuf:"bytes,21,opt,name=CardTradeNo,proto3" json:"CardTradeNo,omitempty"`
	CardId               string   `protobuf:"bytes,22,opt,name=CardId,proto3" json:"CardId,omitempty"`
	FlowNo               string   `protobuf:"bytes,23,opt,name=FlowNo,proto3" json:"FlowNo,omitempty"`
	TransFrom            string   `protobuf:"bytes,24,opt,name=TransFrom,proto3" json:"TransFrom,omitempty"`
	StationMode          string   `protobuf:"bytes,25,opt,name=StationMode,proto3" json:"StationMode,omitempty"`
	EntryNetwork         string   `protobuf:"bytes,26,opt,name=EntryNetwork,proto3" json:"EntryNetwork,omitempty"`
	EntryStationId       string   `protobuf:"bytes,27,opt,name=EntryStationId,proto3" json:"EntryStationId,omitempty"`
	EntryLaneId          string   `protobuf:"bytes,28,opt,name=EntryLaneId,proto3" json:"EntryLaneId,omitempty"`
	EntryOperator        string   `protobuf:"bytes,29,opt,name=EntryOperator,proto3" json:"EntryOperator,omitempty"`
	EntryShift           string   `protobuf:"bytes,30,opt,name=EntryShift,proto3" json:"EntryShift,omitempty"`
	EntryTime            string   `protobuf:"bytes,31,opt,name=EntryTime,proto3" json:"EntryTime,omitempty"`
	FlagStationid        string   `protobuf:"bytes,32,opt,name=FlagStationid,proto3" json:"FlagStationid,omitempty"`
	FlagTime             string   `protobuf:"bytes,33,opt,name=FlagTime,proto3" json:"FlagTime,omitempty"`
	RegVehclass          string   `protobuf:"bytes,34,opt,name=RegVehclass,proto3" json:"RegVehclass,omitempty"`
	RegVehplate          string   `protobuf:"bytes,35,opt,name=RegVehplate,proto3" json:"RegVehplate,omitempty"`
	AntennaID            string   `protobuf:"bytes,36,opt,name=AntennaID,proto3" json:"AntennaID,omitempty"`
	TID                  string   `protobuf:"bytes,37,opt,name=TID,proto3" json:"TID,omitempty"`
	VehColor             string   `protobuf:"bytes,38,opt,name=VehColor,proto3" json:"VehColor,omitempty"`
	TransMemo            string   `protobuf:"bytes,39,opt,name=TransMemo,proto3" json:"TransMemo,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ExitFlowRequest) Reset()         { *m = ExitFlowRequest{} }
func (m *ExitFlowRequest) String() string { return proto.CompactTextString(m) }
func (*ExitFlowRequest) ProtoMessage()    {}
func (*ExitFlowRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0bb7cee52a09eea, []int{8}
}

func (m *ExitFlowRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExitFlowRequest.Unmarshal(m, b)
}
func (m *ExitFlowRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExitFlowRequest.Marshal(b, m, deterministic)
}
func (m *ExitFlowRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExitFlowRequest.Merge(m, src)
}
func (m *ExitFlowRequest) XXX_Size() int {
	return xxx_messageInfo_ExitFlowRequest.Size(m)
}
func (m *ExitFlowRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ExitFlowRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ExitFlowRequest proto.InternalMessageInfo

func (m *ExitFlowRequest) GetVehclass() string {
	if m != nil {
		return m.Vehclass
	}
	return ""
}

func (m *ExitFlowRequest) GetVehplate() string {
	if m != nil {
		return m.Vehplate
	}
	return ""
}

func (m *ExitFlowRequest) GetExitNetwork() string {
	if m != nil {
		return m.ExitNetwork
	}
	return ""
}

func (m *ExitFlowRequest) GetExitStationid() string {
	if m != nil {
		return m.ExitStationid
	}
	return ""
}

func (m *ExitFlowRequest) GetExitLandid() string {
	if m != nil {
		return m.ExitLandid
	}
	return ""
}

func (m *ExitFlowRequest) GetExitOperator() string {
	if m != nil {
		return m.ExitOperator
	}
	return ""
}

func (m *ExitFlowRequest) GetExitShiftdate() string {
	if m != nil {
		return m.ExitShiftdate
	}
	return ""
}

func (m *ExitFlowRequest) GetExitShift() string {
	if m != nil {
		return m.ExitShift
	}
	return ""
}

func (m *ExitFlowRequest) GetPaytype() string {
	if m != nil {
		return m.Paytype
	}
	return ""
}

func (m *ExitFlowRequest) GetPaymethod() string {
	if m != nil {
		return m.Paymethod
	}
	return ""
}

func (m *ExitFlowRequest) GetPayid() string {
	if m != nil {
		return m.Payid
	}
	return ""
}

func (m *ExitFlowRequest) GetTranstime() string {
	if m != nil {
		return m.Transtime
	}
	return ""
}

func (m *ExitFlowRequest) GetPaytime() string {
	if m != nil {
		return m.Paytime
	}
	return ""
}

func (m *ExitFlowRequest) GetToll() string {
	if m != nil {
		return m.Toll
	}
	return ""
}

func (m *ExitFlowRequest) GetGoodsno() string {
	if m != nil {
		return m.Goodsno
	}
	return ""
}

func (m *ExitFlowRequest) GetTradeno() string {
	if m != nil {
		return m.Tradeno
	}
	return ""
}

func (m *ExitFlowRequest) GetPrintFlag() string {
	if m != nil {
		return m.PrintFlag
	}
	return ""
}

func (m *ExitFlowRequest) GetTermid() string {
	if m != nil {
		return m.Termid
	}
	return ""
}

func (m *ExitFlowRequest) GetTermno() string {
	if m != nil {
		return m.Termno
	}
	return ""
}

func (m *ExitFlowRequest) GetTac() string {
	if m != nil {
		return m.Tac
	}
	return ""
}

func (m *ExitFlowRequest) GetCardTradeNo() string {
	if m != nil {
		return m.CardTradeNo
	}
	return ""
}

func (m *ExitFlowRequest) GetCardId() string {
	if m != nil {
		return m.CardId
	}
	return ""
}

func (m *ExitFlowRequest) GetFlowNo() string {
	if m != nil {
		return m.FlowNo
	}
	return ""
}

func (m *ExitFlowRequest) GetTransFrom() string {
	if m != nil {
		return m.TransFrom
	}
	return ""
}

func (m *ExitFlowRequest) GetStationMode() string {
	if m != nil {
		return m.StationMode
	}
	return ""
}

func (m *ExitFlowRequest) GetEntryNetwork() string {
	if m != nil {
		return m.EntryNetwork
	}
	return ""
}

func (m *ExitFlowRequest) GetEntryStationId() string {
	if m != nil {
		return m.EntryStationId
	}
	return ""
}

func (m *ExitFlowRequest) GetEntryLaneId() string {
	if m != nil {
		return m.EntryLaneId
	}
	return ""
}

func (m *ExitFlowRequest) GetEntryOperator() string {
	if m != nil {
		return m.EntryOperator
	}
	return ""
}

func (m *ExitFlowRequest) GetEntryShift() string {
	if m != nil {
		return m.EntryShift
	}
	return ""
}

func (m *ExitFlowRequest) GetEntryTime() string {
	if m != nil {
		return m.EntryTime
	}
	return ""
}

func (m *ExitFlowRequest) GetFlagStationid() string {
	if m != nil {
		return m.FlagStationid
	}
	return ""
}

func (m *ExitFlowRequest) GetFlagTime() string {
	if m != nil {
		return m.FlagTime
	}
	return ""
}

func (m *ExitFlowRequest) GetRegVehclass() string {
	if m != nil {
		return m.RegVehclass
	}
	return ""
}

func (m *ExitFlowRequest) GetRegVehplate() string {
	if m != nil {
		return m.RegVehplate
	}
	return ""
}

func (m *ExitFlowRequest) GetAntennaID() string {
	if m != nil {
		return m.AntennaID
	}
	return ""
}

func (m *ExitFlowRequest) GetTID() string {
	if m != nil {
		return m.TID
	}
	return ""
}

func (m *ExitFlowRequest) GetVehColor() string {
	if m != nil {
		return m.VehColor
	}
	return ""
}

func (m *ExitFlowRequest) GetTransMemo() string {
	if m != nil {
		return m.TransMemo
	}
	return ""
}

type ExitFlowResponse struct {
	FlowNo               string   `protobuf:"bytes,1,opt,name=FlowNo,proto3" json:"FlowNo,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ExitFlowResponse) Reset()         { *m = ExitFlowResponse{} }
func (m *ExitFlowResponse) String() string { return proto.CompactTextString(m) }
func (*ExitFlowResponse) ProtoMessage()    {}
func (*ExitFlowResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0bb7cee52a09eea, []int{9}
}

func (m *ExitFlowResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExitFlowResponse.Unmarshal(m, b)
}
func (m *ExitFlowResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExitFlowResponse.Marshal(b, m, deterministic)
}
func (m *ExitFlowResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExitFlowResponse.Merge(m, src)
}
func (m *ExitFlowResponse) XXX_Size() int {
	return xxx_messageInfo_ExitFlowResponse.Size(m)
}
func (m *ExitFlowResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ExitFlowResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ExitFlowResponse proto.InternalMessageInfo

func (m *ExitFlowResponse) GetFlowNo() string {
	if m != nil {
		return m.FlowNo
	}
	return ""
}

//出口图片数据
type ExitImgAdds struct {
	ExitNetwork          string   `protobuf:"bytes,1,opt,name=ExitNetwork,proto3" json:"ExitNetwork,omitempty"`
	ExitStationid        string   `protobuf:"bytes,2,opt,name=ExitStationid,proto3" json:"ExitStationid,omitempty"`
	ExitLandid           string   `protobuf:"bytes,3,opt,name=ExitLandid,proto3" json:"ExitLandid,omitempty"`
	ExitOperator         string   `protobuf:"bytes,4,opt,name=ExitOperator,proto3" json:"ExitOperator,omitempty"`
	ExitShiftdate        string   `protobuf:"bytes,5,opt,name=ExitShiftdate,proto3" json:"ExitShiftdate,omitempty"`
	ExitShift            string   `protobuf:"bytes,6,opt,name=ExitShift,proto3" json:"ExitShift,omitempty"`
	Transtime            string   `protobuf:"bytes,7,opt,name=Transtime,proto3" json:"Transtime,omitempty"`
	FlowNo               string   `protobuf:"bytes,8,opt,name=FlowNo,proto3" json:"FlowNo,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ExitImgAdds) Reset()         { *m = ExitImgAdds{} }
func (m *ExitImgAdds) String() string { return proto.CompactTextString(m) }
func (*ExitImgAdds) ProtoMessage()    {}
func (*ExitImgAdds) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0bb7cee52a09eea, []int{10}
}

func (m *ExitImgAdds) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExitImgAdds.Unmarshal(m, b)
}
func (m *ExitImgAdds) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExitImgAdds.Marshal(b, m, deterministic)
}
func (m *ExitImgAdds) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExitImgAdds.Merge(m, src)
}
func (m *ExitImgAdds) XXX_Size() int {
	return xxx_messageInfo_ExitImgAdds.Size(m)
}
func (m *ExitImgAdds) XXX_DiscardUnknown() {
	xxx_messageInfo_ExitImgAdds.DiscardUnknown(m)
}

var xxx_messageInfo_ExitImgAdds proto.InternalMessageInfo

func (m *ExitImgAdds) GetExitNetwork() string {
	if m != nil {
		return m.ExitNetwork
	}
	return ""
}

func (m *ExitImgAdds) GetExitStationid() string {
	if m != nil {
		return m.ExitStationid
	}
	return ""
}

func (m *ExitImgAdds) GetExitLandid() string {
	if m != nil {
		return m.ExitLandid
	}
	return ""
}

func (m *ExitImgAdds) GetExitOperator() string {
	if m != nil {
		return m.ExitOperator
	}
	return ""
}

func (m *ExitImgAdds) GetExitShiftdate() string {
	if m != nil {
		return m.ExitShiftdate
	}
	return ""
}

func (m *ExitImgAdds) GetExitShift() string {
	if m != nil {
		return m.ExitShift
	}
	return ""
}

func (m *ExitImgAdds) GetTranstime() string {
	if m != nil {
		return m.Transtime
	}
	return ""
}

func (m *ExitImgAdds) GetFlowNo() string {
	if m != nil {
		return m.FlowNo
	}
	return ""
}

type ExitImgRequest struct {
	AddsInfo             *ExitImgAdds     `protobuf:"bytes,1,opt,name=AddsInfo,proto3" json:"AddsInfo,omitempty"`
	RstVehPlateInfo      *RstVehRecognize `protobuf:"bytes,2,opt,name=RstVehPlateInfo,proto3" json:"RstVehPlateInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *ExitImgRequest) Reset()         { *m = ExitImgRequest{} }
func (m *ExitImgRequest) String() string { return proto.CompactTextString(m) }
func (*ExitImgRequest) ProtoMessage()    {}
func (*ExitImgRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0bb7cee52a09eea, []int{11}
}

func (m *ExitImgRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExitImgRequest.Unmarshal(m, b)
}
func (m *ExitImgRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExitImgRequest.Marshal(b, m, deterministic)
}
func (m *ExitImgRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExitImgRequest.Merge(m, src)
}
func (m *ExitImgRequest) XXX_Size() int {
	return xxx_messageInfo_ExitImgRequest.Size(m)
}
func (m *ExitImgRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ExitImgRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ExitImgRequest proto.InternalMessageInfo

func (m *ExitImgRequest) GetAddsInfo() *ExitImgAdds {
	if m != nil {
		return m.AddsInfo
	}
	return nil
}

func (m *ExitImgRequest) GetRstVehPlateInfo() *RstVehRecognize {
	if m != nil {
		return m.RstVehPlateInfo
	}
	return nil
}

type ExitImgResponse struct {
	FlowNo               string   `protobuf:"bytes,1,opt,name=FlowNo,proto3" json:"FlowNo,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ExitImgResponse) Reset()         { *m = ExitImgResponse{} }
func (m *ExitImgResponse) String() string { return proto.CompactTextString(m) }
func (*ExitImgResponse) ProtoMessage()    {}
func (*ExitImgResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0bb7cee52a09eea, []int{12}
}

func (m *ExitImgResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExitImgResponse.Unmarshal(m, b)
}
func (m *ExitImgResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExitImgResponse.Marshal(b, m, deterministic)
}
func (m *ExitImgResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExitImgResponse.Merge(m, src)
}
func (m *ExitImgResponse) XXX_Size() int {
	return xxx_messageInfo_ExitImgResponse.Size(m)
}
func (m *ExitImgResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ExitImgResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ExitImgResponse proto.InternalMessageInfo

func (m *ExitImgResponse) GetFlowNo() string {
	if m != nil {
		return m.FlowNo
	}
	return ""
}

//设备状态数据
type DevStateRequest struct {
	ExitNetwork          string   `protobuf:"bytes,1,opt,name=ExitNetwork,proto3" json:"ExitNetwork,omitempty"`
	ExitStationid        string   `protobuf:"bytes,2,opt,name=ExitStationid,proto3" json:"ExitStationid,omitempty"`
	ExitLandid           string   `protobuf:"bytes,3,opt,name=ExitLandid,proto3" json:"ExitLandid,omitempty"`
	EquipmentDev         string   `protobuf:"bytes,4,opt,name=EquipmentDev,proto3" json:"EquipmentDev,omitempty"`
	PrinterDev1          string   `protobuf:"bytes,5,opt,name=PrinterDev1,proto3" json:"PrinterDev1,omitempty"`
	PrinterDev2          string   `protobuf:"bytes,6,opt,name=PrinterDev2,proto3" json:"PrinterDev2,omitempty"`
	PlateDev             string   `protobuf:"bytes,7,opt,name=PlateDev,proto3" json:"PlateDev,omitempty"`
	Coil1                string   `protobuf:"bytes,8,opt,name=Coil1,proto3" json:"Coil1,omitempty"`
	Coil2                string   `protobuf:"bytes,9,opt,name=Coil2,proto3" json:"Coil2,omitempty"`
	Scan1                string   `protobuf:"bytes,10,opt,name=Scan1,proto3" json:"Scan1,omitempty"`
	Scan2                string   `protobuf:"bytes,11,opt,name=Scan2,proto3" json:"Scan2,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DevStateRequest) Reset()         { *m = DevStateRequest{} }
func (m *DevStateRequest) String() string { return proto.CompactTextString(m) }
func (*DevStateRequest) ProtoMessage()    {}
func (*DevStateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0bb7cee52a09eea, []int{13}
}

func (m *DevStateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DevStateRequest.Unmarshal(m, b)
}
func (m *DevStateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DevStateRequest.Marshal(b, m, deterministic)
}
func (m *DevStateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DevStateRequest.Merge(m, src)
}
func (m *DevStateRequest) XXX_Size() int {
	return xxx_messageInfo_DevStateRequest.Size(m)
}
func (m *DevStateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DevStateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DevStateRequest proto.InternalMessageInfo

func (m *DevStateRequest) GetExitNetwork() string {
	if m != nil {
		return m.ExitNetwork
	}
	return ""
}

func (m *DevStateRequest) GetExitStationid() string {
	if m != nil {
		return m.ExitStationid
	}
	return ""
}

func (m *DevStateRequest) GetExitLandid() string {
	if m != nil {
		return m.ExitLandid
	}
	return ""
}

func (m *DevStateRequest) GetEquipmentDev() string {
	if m != nil {
		return m.EquipmentDev
	}
	return ""
}

func (m *DevStateRequest) GetPrinterDev1() string {
	if m != nil {
		return m.PrinterDev1
	}
	return ""
}

func (m *DevStateRequest) GetPrinterDev2() string {
	if m != nil {
		return m.PrinterDev2
	}
	return ""
}

func (m *DevStateRequest) GetPlateDev() string {
	if m != nil {
		return m.PlateDev
	}
	return ""
}

func (m *DevStateRequest) GetCoil1() string {
	if m != nil {
		return m.Coil1
	}
	return ""
}

func (m *DevStateRequest) GetCoil2() string {
	if m != nil {
		return m.Coil2
	}
	return ""
}

func (m *DevStateRequest) GetScan1() string {
	if m != nil {
		return m.Scan1
	}
	return ""
}

func (m *DevStateRequest) GetScan2() string {
	if m != nil {
		return m.Scan2
	}
	return ""
}

//远程控制
type ControlRequest struct {
	ExitNetwork          string   `protobuf:"bytes,1,opt,name=ExitNetwork,proto3" json:"ExitNetwork,omitempty"`
	ExitStationid        string   `protobuf:"bytes,2,opt,name=ExitStationid,proto3" json:"ExitStationid,omitempty"`
	ExitLandid           string   `protobuf:"bytes,3,opt,name=ExitLandid,proto3" json:"ExitLandid,omitempty"`
	Cmd                  string   `protobuf:"bytes,4,opt,name=Cmd,proto3" json:"Cmd,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ControlRequest) Reset()         { *m = ControlRequest{} }
func (m *ControlRequest) String() string { return proto.CompactTextString(m) }
func (*ControlRequest) ProtoMessage()    {}
func (*ControlRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0bb7cee52a09eea, []int{14}
}

func (m *ControlRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ControlRequest.Unmarshal(m, b)
}
func (m *ControlRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ControlRequest.Marshal(b, m, deterministic)
}
func (m *ControlRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ControlRequest.Merge(m, src)
}
func (m *ControlRequest) XXX_Size() int {
	return xxx_messageInfo_ControlRequest.Size(m)
}
func (m *ControlRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ControlRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ControlRequest proto.InternalMessageInfo

func (m *ControlRequest) GetExitNetwork() string {
	if m != nil {
		return m.ExitNetwork
	}
	return ""
}

func (m *ControlRequest) GetExitStationid() string {
	if m != nil {
		return m.ExitStationid
	}
	return ""
}

func (m *ControlRequest) GetExitLandid() string {
	if m != nil {
		return m.ExitLandid
	}
	return ""
}

func (m *ControlRequest) GetCmd() string {
	if m != nil {
		return m.Cmd
	}
	return ""
}

type ControlResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ControlResponse) Reset()         { *m = ControlResponse{} }
func (m *ControlResponse) String() string { return proto.CompactTextString(m) }
func (*ControlResponse) ProtoMessage()    {}
func (*ControlResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0bb7cee52a09eea, []int{15}
}

func (m *ControlResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ControlResponse.Unmarshal(m, b)
}
func (m *ControlResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ControlResponse.Marshal(b, m, deterministic)
}
func (m *ControlResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ControlResponse.Merge(m, src)
}
func (m *ControlResponse) XXX_Size() int {
	return xxx_messageInfo_ControlResponse.Size(m)
}
func (m *ControlResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ControlResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ControlResponse proto.InternalMessageInfo

//车辆通行信息
type CarpathRequest struct {
	Vehclass             string   `protobuf:"bytes,1,opt,name=Vehclass,proto3" json:"Vehclass,omitempty"`
	Vehplate             string   `protobuf:"bytes,2,opt,name=Vehplate,proto3" json:"Vehplate,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CarpathRequest) Reset()         { *m = CarpathRequest{} }
func (m *CarpathRequest) String() string { return proto.CompactTextString(m) }
func (*CarpathRequest) ProtoMessage()    {}
func (*CarpathRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0bb7cee52a09eea, []int{16}
}

func (m *CarpathRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CarpathRequest.Unmarshal(m, b)
}
func (m *CarpathRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CarpathRequest.Marshal(b, m, deterministic)
}
func (m *CarpathRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CarpathRequest.Merge(m, src)
}
func (m *CarpathRequest) XXX_Size() int {
	return xxx_messageInfo_CarpathRequest.Size(m)
}
func (m *CarpathRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CarpathRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CarpathRequest proto.InternalMessageInfo

func (m *CarpathRequest) GetVehclass() string {
	if m != nil {
		return m.Vehclass
	}
	return ""
}

func (m *CarpathRequest) GetVehplate() string {
	if m != nil {
		return m.Vehplate
	}
	return ""
}

type CarpathResponse struct {
	EntryNetwork         string   `protobuf:"bytes,1,opt,name=EntryNetwork,proto3" json:"EntryNetwork,omitempty"`
	EntryStationId       string   `protobuf:"bytes,2,opt,name=EntryStationId,proto3" json:"EntryStationId,omitempty"`
	EntryLaneId          string   `protobuf:"bytes,3,opt,name=EntryLaneId,proto3" json:"EntryLaneId,omitempty"`
	EntryOperator        string   `protobuf:"bytes,4,opt,name=EntryOperator,proto3" json:"EntryOperator,omitempty"`
	EntryShift           string   `protobuf:"bytes,5,opt,name=EntryShift,proto3" json:"EntryShift,omitempty"`
	EntryTime            string   `protobuf:"bytes,6,opt,name=EntryTime,proto3" json:"EntryTime,omitempty"`
	FlagStationid        string   `protobuf:"bytes,7,opt,name=FlagStationid,proto3" json:"FlagStationid,omitempty"`
	HasCard              string   `protobuf:"bytes,8,opt,name=HasCard,proto3" json:"HasCard,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CarpathResponse) Reset()         { *m = CarpathResponse{} }
func (m *CarpathResponse) String() string { return proto.CompactTextString(m) }
func (*CarpathResponse) ProtoMessage()    {}
func (*CarpathResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0bb7cee52a09eea, []int{17}
}

func (m *CarpathResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CarpathResponse.Unmarshal(m, b)
}
func (m *CarpathResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CarpathResponse.Marshal(b, m, deterministic)
}
func (m *CarpathResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CarpathResponse.Merge(m, src)
}
func (m *CarpathResponse) XXX_Size() int {
	return xxx_messageInfo_CarpathResponse.Size(m)
}
func (m *CarpathResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CarpathResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CarpathResponse proto.InternalMessageInfo

func (m *CarpathResponse) GetEntryNetwork() string {
	if m != nil {
		return m.EntryNetwork
	}
	return ""
}

func (m *CarpathResponse) GetEntryStationId() string {
	if m != nil {
		return m.EntryStationId
	}
	return ""
}

func (m *CarpathResponse) GetEntryLaneId() string {
	if m != nil {
		return m.EntryLaneId
	}
	return ""
}

func (m *CarpathResponse) GetEntryOperator() string {
	if m != nil {
		return m.EntryOperator
	}
	return ""
}

func (m *CarpathResponse) GetEntryShift() string {
	if m != nil {
		return m.EntryShift
	}
	return ""
}

func (m *CarpathResponse) GetEntryTime() string {
	if m != nil {
		return m.EntryTime
	}
	return ""
}

func (m *CarpathResponse) GetFlagStationid() string {
	if m != nil {
		return m.FlagStationid
	}
	return ""
}

func (m *CarpathResponse) GetHasCard() string {
	if m != nil {
		return m.HasCard
	}
	return ""
}

//自由流通行结果
type ChkFreeflowRequest struct {
	Msgbody              string   `protobuf:"bytes,1,opt,name=msgbody,proto3" json:"msgbody,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChkFreeflowRequest) Reset()         { *m = ChkFreeflowRequest{} }
func (m *ChkFreeflowRequest) String() string { return proto.CompactTextString(m) }
func (*ChkFreeflowRequest) ProtoMessage()    {}
func (*ChkFreeflowRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0bb7cee52a09eea, []int{18}
}

func (m *ChkFreeflowRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChkFreeflowRequest.Unmarshal(m, b)
}
func (m *ChkFreeflowRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChkFreeflowRequest.Marshal(b, m, deterministic)
}
func (m *ChkFreeflowRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChkFreeflowRequest.Merge(m, src)
}
func (m *ChkFreeflowRequest) XXX_Size() int {
	return xxx_messageInfo_ChkFreeflowRequest.Size(m)
}
func (m *ChkFreeflowRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ChkFreeflowRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ChkFreeflowRequest proto.InternalMessageInfo

func (m *ChkFreeflowRequest) GetMsgbody() string {
	if m != nil {
		return m.Msgbody
	}
	return ""
}

type ChkFreeflowResponse struct {
	Msgbody              string   `protobuf:"bytes,1,opt,name=msgbody,proto3" json:"msgbody,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChkFreeflowResponse) Reset()         { *m = ChkFreeflowResponse{} }
func (m *ChkFreeflowResponse) String() string { return proto.CompactTextString(m) }
func (*ChkFreeflowResponse) ProtoMessage()    {}
func (*ChkFreeflowResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0bb7cee52a09eea, []int{19}
}

func (m *ChkFreeflowResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChkFreeflowResponse.Unmarshal(m, b)
}
func (m *ChkFreeflowResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChkFreeflowResponse.Marshal(b, m, deterministic)
}
func (m *ChkFreeflowResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChkFreeflowResponse.Merge(m, src)
}
func (m *ChkFreeflowResponse) XXX_Size() int {
	return xxx_messageInfo_ChkFreeflowResponse.Size(m)
}
func (m *ChkFreeflowResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ChkFreeflowResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ChkFreeflowResponse proto.InternalMessageInfo

func (m *ChkFreeflowResponse) GetMsgbody() string {
	if m != nil {
		return m.Msgbody
	}
	return ""
}

//自由流通行结果通知
type NotifyFreeflowRequest struct {
	Msgbody              string   `protobuf:"bytes,1,opt,name=msgbody,proto3" json:"msgbody,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NotifyFreeflowRequest) Reset()         { *m = NotifyFreeflowRequest{} }
func (m *NotifyFreeflowRequest) String() string { return proto.CompactTextString(m) }
func (*NotifyFreeflowRequest) ProtoMessage()    {}
func (*NotifyFreeflowRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0bb7cee52a09eea, []int{20}
}

func (m *NotifyFreeflowRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NotifyFreeflowRequest.Unmarshal(m, b)
}
func (m *NotifyFreeflowRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NotifyFreeflowRequest.Marshal(b, m, deterministic)
}
func (m *NotifyFreeflowRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NotifyFreeflowRequest.Merge(m, src)
}
func (m *NotifyFreeflowRequest) XXX_Size() int {
	return xxx_messageInfo_NotifyFreeflowRequest.Size(m)
}
func (m *NotifyFreeflowRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_NotifyFreeflowRequest.DiscardUnknown(m)
}

var xxx_messageInfo_NotifyFreeflowRequest proto.InternalMessageInfo

func (m *NotifyFreeflowRequest) GetMsgbody() string {
	if m != nil {
		return m.Msgbody
	}
	return ""
}

type NotifyFreeflowResponse struct {
	Msgbody              string   `protobuf:"bytes,1,opt,name=msgbody,proto3" json:"msgbody,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NotifyFreeflowResponse) Reset()         { *m = NotifyFreeflowResponse{} }
func (m *NotifyFreeflowResponse) String() string { return proto.CompactTextString(m) }
func (*NotifyFreeflowResponse) ProtoMessage()    {}
func (*NotifyFreeflowResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0bb7cee52a09eea, []int{21}
}

func (m *NotifyFreeflowResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NotifyFreeflowResponse.Unmarshal(m, b)
}
func (m *NotifyFreeflowResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NotifyFreeflowResponse.Marshal(b, m, deterministic)
}
func (m *NotifyFreeflowResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NotifyFreeflowResponse.Merge(m, src)
}
func (m *NotifyFreeflowResponse) XXX_Size() int {
	return xxx_messageInfo_NotifyFreeflowResponse.Size(m)
}
func (m *NotifyFreeflowResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_NotifyFreeflowResponse.DiscardUnknown(m)
}

var xxx_messageInfo_NotifyFreeflowResponse proto.InternalMessageInfo

func (m *NotifyFreeflowResponse) GetMsgbody() string {
	if m != nil {
		return m.Msgbody
	}
	return ""
}

func init() {
	proto.RegisterType((*InitRequest)(nil), "pb.InitRequest")
	proto.RegisterType((*InitResponse)(nil), "pb.InitResponse")
	proto.RegisterType((*FeeRequest)(nil), "pb.FeeRequest")
	proto.RegisterType((*FeeResponse)(nil), "pb.FeeResponse")
	proto.RegisterType((*PlatePayCheckRequest)(nil), "pb.PlatePayCheckRequest")
	proto.RegisterType((*PlatePayCheckResponse)(nil), "pb.PlatePayCheckResponse")
	proto.RegisterType((*PayRequest)(nil), "pb.PayRequest")
	proto.RegisterType((*PayResponse)(nil), "pb.PayResponse")
	proto.RegisterType((*ExitFlowRequest)(nil), "pb.ExitFlowRequest")
	proto.RegisterType((*ExitFlowResponse)(nil), "pb.ExitFlowResponse")
	proto.RegisterType((*ExitImgAdds)(nil), "pb.ExitImgAdds")
	proto.RegisterType((*ExitImgRequest)(nil), "pb.ExitImgRequest")
	proto.RegisterType((*ExitImgResponse)(nil), "pb.ExitImgResponse")
	proto.RegisterType((*DevStateRequest)(nil), "pb.DevStateRequest")
	proto.RegisterType((*ControlRequest)(nil), "pb.ControlRequest")
	proto.RegisterType((*ControlResponse)(nil), "pb.ControlResponse")
	proto.RegisterType((*CarpathRequest)(nil), "pb.CarpathRequest")
	proto.RegisterType((*CarpathResponse)(nil), "pb.CarpathResponse")
	proto.RegisterType((*ChkFreeflowRequest)(nil), "pb.ChkFreeflowRequest")
	proto.RegisterType((*ChkFreeflowResponse)(nil), "pb.ChkFreeflowResponse")
	proto.RegisterType((*NotifyFreeflowRequest)(nil), "pb.NotifyFreeflowRequest")
	proto.RegisterType((*NotifyFreeflowResponse)(nil), "pb.NotifyFreeflowResponse")
}

func init() { proto.RegisterFile("Cloud.proto", fileDescriptor_a0bb7cee52a09eea) }

var fileDescriptor_a0bb7cee52a09eea = []byte{
	// 1165 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x57, 0xcb, 0x6e, 0x23, 0x45,
	0x14, 0x95, 0xed, 0xc4, 0x8e, 0xaf, 0x33, 0x76, 0xa6, 0xf3, 0xa0, 0x08, 0x21, 0x64, 0x9a, 0x61,
	0x86, 0x87, 0x14, 0x94, 0xb0, 0x66, 0x31, 0xb2, 0x09, 0x63, 0x31, 0x13, 0x2c, 0xc7, 0xca, 0x9a,
	0x8a, 0xbb, 0x62, 0xb7, 0xd2, 0xae, 0x72, 0xba, 0x2b, 0x99, 0x31, 0xe2, 0x0b, 0xd8, 0xb2, 0x64,
	0x83, 0xc4, 0x82, 0x2f, 0xe2, 0x17, 0xf8, 0x0e, 0x74, 0xeb, 0xd5, 0xd5, 0x2d, 0x26, 0xb6, 0x84,
	0x34, 0x3b, 0x9f, 0x53, 0x8f, 0xfb, 0x3a, 0x75, 0x6f, 0x1b, 0x5a, 0xdd, 0x44, 0xdc, 0x45, 0xc7,
	0xf3, 0x54, 0x48, 0x11, 0x54, 0xe7, 0x57, 0xfb, 0xad, 0x41, 0x42, 0x25, 0xd3, 0x44, 0xf8, 0x1c,
	0x5a, 0x7d, 0x1e, 0xcb, 0x21, 0xbb, 0xbd, 0x63, 0x99, 0x0c, 0x08, 0x34, 0x12, 0xca, 0xd9, 0x0f,
	0x6c, 0x41, 0x2a, 0x47, 0x95, 0xcf, 0x9b, 0x43, 0x0b, 0xc3, 0x36, 0x6c, 0xea, 0x8d, 0xd9, 0x5c,
	0xf0, 0x8c, 0x85, 0x7f, 0x54, 0x00, 0xce, 0x18, 0xb3, 0x07, 0xf7, 0x61, 0xe3, 0x9e, 0x4d, 0xe7,
	0x78, 0xb3, 0x39, 0xe9, 0xb0, 0x59, 0x1b, 0x27, 0x34, 0xcb, 0x48, 0xd5, 0xad, 0x29, 0x1c, 0x1c,
	0x02, 0x30, 0x2e, 0xd3, 0x45, 0x26, 0x69, 0x1c, 0x91, 0x9a, 0x5a, 0xf5, 0x98, 0xe0, 0x00, 0x9a,
	0xec, 0x6d, 0x2c, 0xf5, 0xf2, 0x9a, 0x5a, 0xce, 0x09, 0x5c, 0xbd, 0x4e, 0xe8, 0x44, 0xaf, 0xae,
	0xeb, 0x55, 0x47, 0x84, 0x4f, 0xa0, 0xa5, 0x3c, 0xd4, 0x1e, 0x07, 0x01, 0xac, 0x49, 0x91, 0x24,
	0xc6, 0x3d, 0xf5, 0x3b, 0xfc, 0x09, 0x76, 0x54, 0x36, 0x06, 0x74, 0xd1, 0x9d, 0xb2, 0xf1, 0x8d,
	0x17, 0xce, 0x65, 0x29, 0x9c, 0x4b, 0x2f, 0x9c, 0xcb, 0x52, 0x38, 0x16, 0x07, 0x5b, 0x50, 0x1b,
	0xf5, 0x7b, 0x26, 0x0e, 0xfc, 0x19, 0xde, 0xc2, 0x6e, 0xc9, 0x82, 0x71, 0xe7, 0x08, 0x5a, 0x96,
	0xb8, 0x4b, 0xa4, 0xb1, 0xe2, 0x53, 0x05, 0x27, 0xaa, 0x0f, 0x38, 0x51, 0x2b, 0x3a, 0x11, 0xfe,
	0x53, 0x01, 0x18, 0xd0, 0x85, 0x8d, 0xe5, 0x10, 0xe0, 0xc7, 0x39, 0x4b, 0xa9, 0x14, 0x69, 0x1c,
	0x19, 0x3b, 0x1e, 0x83, 0x35, 0xbf, 0x98, 0xc6, 0xd7, 0x32, 0x8e, 0x8c, 0x15, 0x0b, 0x31, 0xbd,
	0xa3, 0x94, 0xf2, 0xac, 0x87, 0x1e, 0x68, 0x2b, 0x39, 0x81, 0xe7, 0x06, 0x74, 0x21, 0x17, 0x73,
	0x66, 0x0a, 0x63, 0xa1, 0x59, 0xe9, 0x8a, 0x88, 0x99, 0xa2, 0x58, 0x58, 0x08, 0xa9, 0x5e, 0x0a,
	0x29, 0x80, 0xb5, 0x11, 0xd6, 0xa7, 0xa1, 0xeb, 0x83, 0xbf, 0x9d, 0x07, 0x32, 0x9e, 0x31, 0xb2,
	0xe1, 0x79, 0x80, 0x44, 0xf8, 0x57, 0x05, 0x5a, 0x2a, 0x50, 0x93, 0x52, 0xcf, 0xa3, 0x4a, 0xd1,
	0xa3, 0x03, 0x68, 0x0e, 0xe8, 0x62, 0xc6, 0xe4, 0x54, 0xd8, 0x28, 0x73, 0x02, 0xcf, 0x7d, 0x2f,
	0x44, 0x94, 0x71, 0x61, 0xa2, 0xb4, 0x10, 0x57, 0x46, 0x29, 0x8d, 0x18, 0x17, 0x36, 0x46, 0x03,
	0x9d, 0xb7, 0xeb, 0x9e, 0xb7, 0xc6, 0x3e, 0xfa, 0x5a, 0xcf, 0xed, 0xa3, 0xa7, 0xbf, 0x37, 0xa1,
	0xf3, 0xdd, 0xdb, 0x58, 0x9e, 0x25, 0xe2, 0x4d, 0x51, 0x63, 0xba, 0x84, 0x95, 0x92, 0x8e, 0x1e,
	0x2a, 0xfd, 0x11, 0xb4, 0xf0, 0xaa, 0x73, 0x26, 0xdf, 0x88, 0xf4, 0xc6, 0x78, 0xec, 0x53, 0xc1,
	0x53, 0x78, 0x84, 0xf0, 0x42, 0x52, 0x19, 0x0b, 0xee, 0x1e, 0x4e, 0x91, 0x44, 0x5d, 0x20, 0xf1,
	0x8a, 0xf2, 0xc8, 0xbd, 0x1e, 0x8f, 0x09, 0x42, 0xd8, 0x44, 0x64, 0x95, 0x62, 0x42, 0x2a, 0x70,
	0xce, 0x12, 0x0a, 0x26, 0x42, 0x67, 0x1b, 0x9e, 0x25, 0x4b, 0x62, 0xf6, 0x1d, 0x61, 0xab, 0xe8,
	0x08, 0xbf, 0x6a, 0xcd, 0x07, 0xaa, 0x06, 0xe5, 0xaa, 0xed, 0xc0, 0xfa, 0x80, 0x2e, 0xe2, 0x88,
	0xb4, 0xd4, 0x8a, 0x06, 0x45, 0xc5, 0x6c, 0x96, 0x14, 0xe3, 0x57, 0xe8, 0x51, 0xa1, 0x42, 0xae,
	0x9e, 0xed, 0x62, 0x3d, 0xad, 0x2e, 0x3a, 0xef, 0xd4, 0xc5, 0x56, 0x51, 0x17, 0xe8, 0x73, 0x1a,
	0x73, 0x79, 0x96, 0xd0, 0x09, 0x79, 0x6c, 0x7c, 0xb6, 0x44, 0xb0, 0x07, 0xf5, 0x11, 0x4b, 0x67,
	0x71, 0x44, 0x02, 0xb5, 0x64, 0x90, 0xe5, 0xb9, 0x20, 0xdb, 0x39, 0xcf, 0x85, 0xea, 0x27, 0x74,
	0x4c, 0x76, 0x4c, 0x3f, 0xa1, 0x63, 0xd5, 0x36, 0x68, 0x1a, 0x29, 0x73, 0xe7, 0x82, 0xec, 0x9a,
	0xb6, 0x91, 0x53, 0x78, 0x17, 0xc2, 0x7e, 0x44, 0xf6, 0xf4, 0x5d, 0x1a, 0x21, 0x8f, 0xf2, 0x3b,
	0x17, 0xe4, 0x03, 0xcd, 0x6b, 0xe4, 0x32, 0x76, 0x96, 0x8a, 0x19, 0x21, 0x5e, 0xc6, 0x90, 0x40,
	0x7b, 0x46, 0x32, 0xaf, 0xf1, 0x3d, 0x7f, 0xa8, 0xed, 0x79, 0x94, 0xd2, 0x09, 0x36, 0x6c, 0x2b,
	0xc8, 0x7d, 0xa3, 0x13, 0x8f, 0x0b, 0x9e, 0x41, 0x5b, 0x61, 0x73, 0xae, 0x1f, 0x91, 0x8f, 0xd4,
	0xae, 0x12, 0xab, 0xb4, 0x8d, 0xcc, 0x2b, 0xca, 0x59, 0x3f, 0x22, 0x07, 0x46, 0xdb, 0x39, 0xa5,
	0x14, 0x87, 0xd0, 0xc9, 0xf2, 0x63, 0xa3, 0x38, 0x9f, 0x54, 0xda, 0x56, 0x37, 0x2b, 0xc9, 0x1d,
	0x1a, 0x6d, 0x3b, 0x46, 0x29, 0x12, 0xd1, 0x08, 0x95, 0xf0, 0x89, 0x51, 0xa4, 0x25, 0xd0, 0x06,
	0x56, 0x2b, 0x7f, 0x3f, 0x47, 0xda, 0x46, 0x81, 0xc4, 0x37, 0x8a, 0x84, 0xba, 0xe2, 0x89, 0x7e,
	0xa3, 0x16, 0x63, 0x1c, 0x43, 0x36, 0x71, 0xcf, 0x3b, 0xd4, 0x71, 0x78, 0x54, 0xbe, 0x43, 0x3f,
	0xf2, 0x4f, 0xfd, 0x1d, 0xfa, 0x9d, 0x1f, 0x40, 0xf3, 0x05, 0x97, 0x8c, 0x73, 0xda, 0xef, 0x91,
	0xa7, 0xda, 0x47, 0x47, 0xd8, 0x49, 0xf3, 0x99, 0x9b, 0x34, 0xa6, 0x67, 0x74, 0x45, 0x22, 0x52,
	0xf2, 0xcc, 0xf5, 0x0c, 0x85, 0x5d, 0x8d, 0x5f, 0xb3, 0x99, 0x20, 0xcf, 0xbd, 0x1a, 0x23, 0x11,
	0x7e, 0x09, 0x5b, 0x79, 0x73, 0x32, 0xbd, 0x34, 0x57, 0x4b, 0xc5, 0x57, 0x4b, 0xf8, 0x5b, 0x55,
	0xb7, 0x9f, 0xfe, 0x6c, 0xf2, 0x22, 0x8a, 0xb2, 0x72, 0x37, 0xaa, 0xac, 0xd0, 0x8d, 0xaa, 0xcb,
	0xbb, 0x51, 0x6d, 0x69, 0x37, 0x5a, 0x5b, 0xa5, 0x1b, 0xad, 0x2f, 0xed, 0x46, 0xf5, 0x72, 0x37,
	0x2a, 0xf4, 0x8f, 0x46, 0xb9, 0x7f, 0xe4, 0x59, 0xd9, 0x28, 0x64, 0xe5, 0x17, 0x68, 0x9b, 0xa4,
	0xd8, 0xee, 0xfe, 0x15, 0x6c, 0x60, 0x7e, 0xfa, 0xfc, 0x5a, 0x67, 0xb0, 0x75, 0xda, 0x39, 0x9e,
	0x5f, 0x1d, 0x7b, 0xa9, 0x1b, 0xba, 0x0d, 0xc1, 0xb7, 0xd0, 0x19, 0x66, 0xf2, 0x92, 0x4d, 0xd5,
	0xa7, 0x82, 0x3a, 0x53, 0x55, 0x67, 0xb6, 0xf1, 0x8c, 0x5e, 0x1a, 0xb2, 0xb1, 0x98, 0xf0, 0xf8,
	0x67, 0x36, 0x2c, 0xef, 0x0d, 0xbf, 0xd0, 0xc3, 0x45, 0x59, 0x5f, 0x52, 0xbe, 0xbf, 0xab, 0xd0,
	0xe9, 0xb1, 0x7b, 0xcc, 0xbb, 0xfb, 0x76, 0x7b, 0x9f, 0x25, 0xbc, 0xbd, 0x8b, 0xe7, 0x33, 0xc6,
	0x65, 0x8f, 0xdd, 0xbb, 0x12, 0x7a, 0x1c, 0xfa, 0xa2, 0xba, 0x25, 0x4b, 0x7b, 0xec, 0xfe, 0xc4,
	0x14, 0xd0, 0xa7, 0x8a, 0x3b, 0x4e, 0x4d, 0x01, 0x7d, 0x0a, 0x1f, 0x82, 0xca, 0x0d, 0xda, 0xd0,
	0x15, 0x74, 0x18, 0x87, 0x46, 0x57, 0xc4, 0xc9, 0x89, 0xa9, 0x9f, 0x06, 0x96, 0x3d, 0x35, 0x03,
	0x48, 0x03, 0x64, 0x2f, 0xc6, 0x94, 0x9f, 0x98, 0xd1, 0xa3, 0x81, 0x65, 0x4f, 0xed, 0xd8, 0x51,
	0x20, 0xfc, 0xb5, 0x02, 0xed, 0xae, 0xe0, 0x32, 0x15, 0xc9, 0xfb, 0x4e, 0xeb, 0x16, 0xd4, 0xba,
	0x33, 0x3b, 0xe3, 0xf1, 0x67, 0xf8, 0x18, 0x3a, 0xce, 0x17, 0xf3, 0xb9, 0xfe, 0x12, 0xda, 0x5d,
	0x9a, 0xce, 0xa9, 0x9c, 0xfe, 0xcf, 0xcf, 0x8f, 0xf0, 0xcf, 0x2a, 0x74, 0xdc, 0x55, 0x46, 0x6d,
	0xe5, 0x11, 0x50, 0x59, 0x69, 0x04, 0x54, 0x57, 0x19, 0x01, 0xb5, 0x15, 0x46, 0xc0, 0xda, 0xf2,
	0x11, 0xb0, 0xfe, 0xf0, 0x08, 0xa8, 0x2f, 0x1d, 0x01, 0x8d, 0xff, 0x1a, 0x01, 0x04, 0x1a, 0x2f,
	0x69, 0x86, 0xf3, 0xd5, 0xe8, 0xc9, 0xc2, 0xf0, 0x18, 0x82, 0xee, 0xf4, 0xe6, 0x2c, 0x65, 0xec,
	0xda, 0xfb, 0xe4, 0x23, 0xd0, 0x98, 0x65, 0x93, 0x2b, 0x11, 0xb9, 0xbf, 0x57, 0x06, 0x86, 0x5f,
	0xc3, 0x76, 0x61, 0x7f, 0xfe, 0x45, 0xfb, 0x8e, 0x03, 0x27, 0xb0, 0x7b, 0x2e, 0x64, 0x7c, 0xbd,
	0x58, 0xdd, 0xc6, 0x29, 0xec, 0x95, 0x8f, 0x2c, 0x33, 0x73, 0x55, 0x57, 0x7f, 0x13, 0xbf, 0xf9,
	0x37, 0x00, 0x00, 0xff, 0xff, 0xc7, 0xa6, 0x8a, 0xa5, 0x46, 0x0e, 0x00, 0x00,
}
