// Code generated by protoc-gen-go. DO NOT EDIT.
// source: Etc.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//初始化
type ETCAntInitRequest struct {
	Key                  string   `protobuf:"bytes,1,opt,name=Key,proto3" json:"Key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ETCAntInitRequest) Reset()         { *m = ETCAntInitRequest{} }
func (m *ETCAntInitRequest) String() string { return proto.CompactTextString(m) }
func (*ETCAntInitRequest) ProtoMessage()    {}
func (*ETCAntInitRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f08fa82c58da1760, []int{0}
}

func (m *ETCAntInitRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ETCAntInitRequest.Unmarshal(m, b)
}
func (m *ETCAntInitRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ETCAntInitRequest.Marshal(b, m, deterministic)
}
func (m *ETCAntInitRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ETCAntInitRequest.Merge(m, src)
}
func (m *ETCAntInitRequest) XXX_Size() int {
	return xxx_messageInfo_ETCAntInitRequest.Size(m)
}
func (m *ETCAntInitRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ETCAntInitRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ETCAntInitRequest proto.InternalMessageInfo

func (m *ETCAntInitRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type ETCAntInitResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ETCAntInitResponse) Reset()         { *m = ETCAntInitResponse{} }
func (m *ETCAntInitResponse) String() string { return proto.CompactTextString(m) }
func (*ETCAntInitResponse) ProtoMessage()    {}
func (*ETCAntInitResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f08fa82c58da1760, []int{1}
}

func (m *ETCAntInitResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ETCAntInitResponse.Unmarshal(m, b)
}
func (m *ETCAntInitResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ETCAntInitResponse.Marshal(b, m, deterministic)
}
func (m *ETCAntInitResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ETCAntInitResponse.Merge(m, src)
}
func (m *ETCAntInitResponse) XXX_Size() int {
	return xxx_messageInfo_ETCAntInitResponse.Size(m)
}
func (m *ETCAntInitResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ETCAntInitResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ETCAntInitResponse proto.InternalMessageInfo

//天线状态
type ETCAntState struct {
	AntNo                string   `protobuf:"bytes,1,opt,name=AntNo,proto3" json:"AntNo,omitempty"`
	State                string   `protobuf:"bytes,2,opt,name=State,proto3" json:"State,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ETCAntState) Reset()         { *m = ETCAntState{} }
func (m *ETCAntState) String() string { return proto.CompactTextString(m) }
func (*ETCAntState) ProtoMessage()    {}
func (*ETCAntState) Descriptor() ([]byte, []int) {
	return fileDescriptor_f08fa82c58da1760, []int{2}
}

func (m *ETCAntState) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ETCAntState.Unmarshal(m, b)
}
func (m *ETCAntState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ETCAntState.Marshal(b, m, deterministic)
}
func (m *ETCAntState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ETCAntState.Merge(m, src)
}
func (m *ETCAntState) XXX_Size() int {
	return xxx_messageInfo_ETCAntState.Size(m)
}
func (m *ETCAntState) XXX_DiscardUnknown() {
	xxx_messageInfo_ETCAntState.DiscardUnknown(m)
}

var xxx_messageInfo_ETCAntState proto.InternalMessageInfo

func (m *ETCAntState) GetAntNo() string {
	if m != nil {
		return m.AntNo
	}
	return ""
}

func (m *ETCAntState) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

type ETCAntStateReport struct {
	Key                  string         `protobuf:"bytes,1,opt,name=Key,proto3" json:"Key,omitempty"`
	State                []*ETCAntState `protobuf:"bytes,2,rep,name=State,proto3" json:"State,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *ETCAntStateReport) Reset()         { *m = ETCAntStateReport{} }
func (m *ETCAntStateReport) String() string { return proto.CompactTextString(m) }
func (*ETCAntStateReport) ProtoMessage()    {}
func (*ETCAntStateReport) Descriptor() ([]byte, []int) {
	return fileDescriptor_f08fa82c58da1760, []int{3}
}

func (m *ETCAntStateReport) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ETCAntStateReport.Unmarshal(m, b)
}
func (m *ETCAntStateReport) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ETCAntStateReport.Marshal(b, m, deterministic)
}
func (m *ETCAntStateReport) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ETCAntStateReport.Merge(m, src)
}
func (m *ETCAntStateReport) XXX_Size() int {
	return xxx_messageInfo_ETCAntStateReport.Size(m)
}
func (m *ETCAntStateReport) XXX_DiscardUnknown() {
	xxx_messageInfo_ETCAntStateReport.DiscardUnknown(m)
}

var xxx_messageInfo_ETCAntStateReport proto.InternalMessageInfo

func (m *ETCAntStateReport) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *ETCAntStateReport) GetState() []*ETCAntState {
	if m != nil {
		return m.State
	}
	return nil
}

//交互信息
type ETCAntReadRequest struct {
	Key                  string   `protobuf:"bytes,1,opt,name=Key,proto3" json:"Key,omitempty"`
	AntNo                string   `protobuf:"bytes,2,opt,name=AntNo,proto3" json:"AntNo,omitempty"`
	PsamTermid           string   `protobuf:"bytes,3,opt,name=PsamTermid,proto3" json:"PsamTermid,omitempty"`
	Msg                  string   `protobuf:"bytes,4,opt,name=Msg,proto3" json:"Msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ETCAntReadRequest) Reset()         { *m = ETCAntReadRequest{} }
func (m *ETCAntReadRequest) String() string { return proto.CompactTextString(m) }
func (*ETCAntReadRequest) ProtoMessage()    {}
func (*ETCAntReadRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f08fa82c58da1760, []int{4}
}

func (m *ETCAntReadRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ETCAntReadRequest.Unmarshal(m, b)
}
func (m *ETCAntReadRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ETCAntReadRequest.Marshal(b, m, deterministic)
}
func (m *ETCAntReadRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ETCAntReadRequest.Merge(m, src)
}
func (m *ETCAntReadRequest) XXX_Size() int {
	return xxx_messageInfo_ETCAntReadRequest.Size(m)
}
func (m *ETCAntReadRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ETCAntReadRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ETCAntReadRequest proto.InternalMessageInfo

func (m *ETCAntReadRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *ETCAntReadRequest) GetAntNo() string {
	if m != nil {
		return m.AntNo
	}
	return ""
}

func (m *ETCAntReadRequest) GetPsamTermid() string {
	if m != nil {
		return m.PsamTermid
	}
	return ""
}

func (m *ETCAntReadRequest) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type ETCAntReadResponse struct {
	Key                  string   `protobuf:"bytes,1,opt,name=Key,proto3" json:"Key,omitempty"`
	AntNo                string   `protobuf:"bytes,2,opt,name=AntNo,proto3" json:"AntNo,omitempty"`
	Msg                  string   `protobuf:"bytes,3,opt,name=Msg,proto3" json:"Msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ETCAntReadResponse) Reset()         { *m = ETCAntReadResponse{} }
func (m *ETCAntReadResponse) String() string { return proto.CompactTextString(m) }
func (*ETCAntReadResponse) ProtoMessage()    {}
func (*ETCAntReadResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f08fa82c58da1760, []int{5}
}

func (m *ETCAntReadResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ETCAntReadResponse.Unmarshal(m, b)
}
func (m *ETCAntReadResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ETCAntReadResponse.Marshal(b, m, deterministic)
}
func (m *ETCAntReadResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ETCAntReadResponse.Merge(m, src)
}
func (m *ETCAntReadResponse) XXX_Size() int {
	return xxx_messageInfo_ETCAntReadResponse.Size(m)
}
func (m *ETCAntReadResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ETCAntReadResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ETCAntReadResponse proto.InternalMessageInfo

func (m *ETCAntReadResponse) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *ETCAntReadResponse) GetAntNo() string {
	if m != nil {
		return m.AntNo
	}
	return ""
}

func (m *ETCAntReadResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func init() {
	proto.RegisterType((*ETCAntInitRequest)(nil), "pb.ETCAntInitRequest")
	proto.RegisterType((*ETCAntInitResponse)(nil), "pb.ETCAntInitResponse")
	proto.RegisterType((*ETCAntState)(nil), "pb.ETCAntState")
	proto.RegisterType((*ETCAntStateReport)(nil), "pb.ETCAntStateReport")
	proto.RegisterType((*ETCAntReadRequest)(nil), "pb.ETCAntReadRequest")
	proto.RegisterType((*ETCAntReadResponse)(nil), "pb.ETCAntReadResponse")
}

func init() { proto.RegisterFile("Etc.proto", fileDescriptor_f08fa82c58da1760) }

var fileDescriptor_f08fa82c58da1760 = []byte{
	// 220 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x74, 0x2d, 0x49, 0xd6,
	0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2a, 0x48, 0x52, 0x52, 0xe5, 0x12, 0x74, 0x0d, 0x71,
	0x76, 0xcc, 0x2b, 0xf1, 0xcc, 0xcb, 0x2c, 0x09, 0x4a, 0x2d, 0x2c, 0x4d, 0x2d, 0x2e, 0x11, 0x12,
	0xe0, 0x62, 0xf6, 0x4e, 0xad, 0x94, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x02, 0x31, 0x95, 0x44,
	0xb8, 0x84, 0x90, 0x95, 0x15, 0x17, 0xe4, 0xe7, 0x15, 0xa7, 0x2a, 0x59, 0x72, 0x71, 0x43, 0x44,
	0x83, 0x4b, 0x12, 0x4b, 0x52, 0x85, 0x44, 0xb8, 0x58, 0x1d, 0xf3, 0x4a, 0xfc, 0xf2, 0xa1, 0x1a,
	0x21, 0x1c, 0x90, 0x28, 0x58, 0x5a, 0x82, 0x09, 0x22, 0x0a, 0xe6, 0x28, 0xf9, 0xc0, 0xec, 0x05,
	0x73, 0x83, 0x52, 0x0b, 0xf2, 0x8b, 0xb0, 0xd8, 0x2b, 0xa4, 0x8a, 0xd0, 0xcc, 0xac, 0xc1, 0x6d,
	0xc4, 0xaf, 0x57, 0x90, 0xa4, 0x87, 0xac, 0x0f, 0x6a, 0x5a, 0x2e, 0xcc, 0xb4, 0xa0, 0xd4, 0xc4,
	0x14, 0x9c, 0xbe, 0x40, 0x38, 0x90, 0x09, 0xd9, 0x81, 0x72, 0x5c, 0x5c, 0x01, 0xc5, 0x89, 0xb9,
	0x21, 0xa9, 0x45, 0xb9, 0x99, 0x29, 0x12, 0xcc, 0x60, 0x29, 0x24, 0x11, 0x90, 0x39, 0xbe, 0xc5,
	0xe9, 0x12, 0x2c, 0x10, 0x73, 0x7c, 0x8b, 0xd3, 0x95, 0xfc, 0x60, 0xa1, 0x01, 0xb1, 0x0e, 0x12,
	0x1a, 0x44, 0xdb, 0x07, 0x35, 0x8f, 0x19, 0x6e, 0x5e, 0x12, 0x1b, 0x38, 0x3e, 0x8c, 0x01, 0x01,
	0x00, 0x00, 0xff, 0xff, 0x6a, 0x3a, 0xf5, 0x6d, 0x9c, 0x01, 0x00, 0x00,
}
