// Code generated by protoc-gen-go. DO NOT EDIT.
// source: Feedisp.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//状态
type FeedispStateReport struct {
	FeedispState         string   `protobuf:"bytes,1,opt,name=FeedispState,proto3" json:"FeedispState,omitempty"`
	AlarmState           string   `protobuf:"bytes,2,opt,name=AlarmState,proto3" json:"AlarmState,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FeedispStateReport) Reset()         { *m = FeedispStateReport{} }
func (m *FeedispStateReport) String() string { return proto.CompactTextString(m) }
func (*FeedispStateReport) ProtoMessage()    {}
func (*FeedispStateReport) Descriptor() ([]byte, []int) {
	return fileDescriptor_3d2ecd61b5f4c1b6, []int{0}
}

func (m *FeedispStateReport) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FeedispStateReport.Unmarshal(m, b)
}
func (m *FeedispStateReport) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FeedispStateReport.Marshal(b, m, deterministic)
}
func (m *FeedispStateReport) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FeedispStateReport.Merge(m, src)
}
func (m *FeedispStateReport) XXX_Size() int {
	return xxx_messageInfo_FeedispStateReport.Size(m)
}
func (m *FeedispStateReport) XXX_DiscardUnknown() {
	xxx_messageInfo_FeedispStateReport.DiscardUnknown(m)
}

var xxx_messageInfo_FeedispStateReport proto.InternalMessageInfo

func (m *FeedispStateReport) GetFeedispState() string {
	if m != nil {
		return m.FeedispState
	}
	return ""
}

func (m *FeedispStateReport) GetAlarmState() string {
	if m != nil {
		return m.AlarmState
	}
	return ""
}

type FeedispShowRequest struct {
	Line1                string   `protobuf:"bytes,1,opt,name=Line1,proto3" json:"Line1,omitempty"`
	Line2                string   `protobuf:"bytes,2,opt,name=Line2,proto3" json:"Line2,omitempty"`
	Line3                string   `protobuf:"bytes,3,opt,name=Line3,proto3" json:"Line3,omitempty"`
	Color1               string   `protobuf:"bytes,4,opt,name=Color1,proto3" json:"Color1,omitempty"`
	Color2               string   `protobuf:"bytes,5,opt,name=Color2,proto3" json:"Color2,omitempty"`
	Color3               string   `protobuf:"bytes,6,opt,name=Color3,proto3" json:"Color3,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FeedispShowRequest) Reset()         { *m = FeedispShowRequest{} }
func (m *FeedispShowRequest) String() string { return proto.CompactTextString(m) }
func (*FeedispShowRequest) ProtoMessage()    {}
func (*FeedispShowRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3d2ecd61b5f4c1b6, []int{1}
}

func (m *FeedispShowRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FeedispShowRequest.Unmarshal(m, b)
}
func (m *FeedispShowRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FeedispShowRequest.Marshal(b, m, deterministic)
}
func (m *FeedispShowRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FeedispShowRequest.Merge(m, src)
}
func (m *FeedispShowRequest) XXX_Size() int {
	return xxx_messageInfo_FeedispShowRequest.Size(m)
}
func (m *FeedispShowRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FeedispShowRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FeedispShowRequest proto.InternalMessageInfo

func (m *FeedispShowRequest) GetLine1() string {
	if m != nil {
		return m.Line1
	}
	return ""
}

func (m *FeedispShowRequest) GetLine2() string {
	if m != nil {
		return m.Line2
	}
	return ""
}

func (m *FeedispShowRequest) GetLine3() string {
	if m != nil {
		return m.Line3
	}
	return ""
}

func (m *FeedispShowRequest) GetColor1() string {
	if m != nil {
		return m.Color1
	}
	return ""
}

func (m *FeedispShowRequest) GetColor2() string {
	if m != nil {
		return m.Color2
	}
	return ""
}

func (m *FeedispShowRequest) GetColor3() string {
	if m != nil {
		return m.Color3
	}
	return ""
}

type FeedispShowResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FeedispShowResponse) Reset()         { *m = FeedispShowResponse{} }
func (m *FeedispShowResponse) String() string { return proto.CompactTextString(m) }
func (*FeedispShowResponse) ProtoMessage()    {}
func (*FeedispShowResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3d2ecd61b5f4c1b6, []int{2}
}

func (m *FeedispShowResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FeedispShowResponse.Unmarshal(m, b)
}
func (m *FeedispShowResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FeedispShowResponse.Marshal(b, m, deterministic)
}
func (m *FeedispShowResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FeedispShowResponse.Merge(m, src)
}
func (m *FeedispShowResponse) XXX_Size() int {
	return xxx_messageInfo_FeedispShowResponse.Size(m)
}
func (m *FeedispShowResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FeedispShowResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FeedispShowResponse proto.InternalMessageInfo

type FeedispAlarmRequest struct {
	AlarmValue           string   `protobuf:"bytes,1,opt,name=AlarmValue,proto3" json:"AlarmValue,omitempty"`
	AlarmTm              string   `protobuf:"bytes,2,opt,name=AlarmTm,proto3" json:"AlarmTm,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FeedispAlarmRequest) Reset()         { *m = FeedispAlarmRequest{} }
func (m *FeedispAlarmRequest) String() string { return proto.CompactTextString(m) }
func (*FeedispAlarmRequest) ProtoMessage()    {}
func (*FeedispAlarmRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3d2ecd61b5f4c1b6, []int{3}
}

func (m *FeedispAlarmRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FeedispAlarmRequest.Unmarshal(m, b)
}
func (m *FeedispAlarmRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FeedispAlarmRequest.Marshal(b, m, deterministic)
}
func (m *FeedispAlarmRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FeedispAlarmRequest.Merge(m, src)
}
func (m *FeedispAlarmRequest) XXX_Size() int {
	return xxx_messageInfo_FeedispAlarmRequest.Size(m)
}
func (m *FeedispAlarmRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FeedispAlarmRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FeedispAlarmRequest proto.InternalMessageInfo

func (m *FeedispAlarmRequest) GetAlarmValue() string {
	if m != nil {
		return m.AlarmValue
	}
	return ""
}

func (m *FeedispAlarmRequest) GetAlarmTm() string {
	if m != nil {
		return m.AlarmTm
	}
	return ""
}

type FeedispAlarmResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FeedispAlarmResponse) Reset()         { *m = FeedispAlarmResponse{} }
func (m *FeedispAlarmResponse) String() string { return proto.CompactTextString(m) }
func (*FeedispAlarmResponse) ProtoMessage()    {}
func (*FeedispAlarmResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3d2ecd61b5f4c1b6, []int{4}
}

func (m *FeedispAlarmResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FeedispAlarmResponse.Unmarshal(m, b)
}
func (m *FeedispAlarmResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FeedispAlarmResponse.Marshal(b, m, deterministic)
}
func (m *FeedispAlarmResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FeedispAlarmResponse.Merge(m, src)
}
func (m *FeedispAlarmResponse) XXX_Size() int {
	return xxx_messageInfo_FeedispAlarmResponse.Size(m)
}
func (m *FeedispAlarmResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FeedispAlarmResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FeedispAlarmResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*FeedispStateReport)(nil), "pb.FeedispStateReport")
	proto.RegisterType((*FeedispShowRequest)(nil), "pb.FeedispShowRequest")
	proto.RegisterType((*FeedispShowResponse)(nil), "pb.FeedispShowResponse")
	proto.RegisterType((*FeedispAlarmRequest)(nil), "pb.FeedispAlarmRequest")
	proto.RegisterType((*FeedispAlarmResponse)(nil), "pb.FeedispAlarmResponse")
}

func init() { proto.RegisterFile("Feedisp.proto", fileDescriptor_3d2ecd61b5f4c1b6) }

var fileDescriptor_3d2ecd61b5f4c1b6 = []byte{
	// 220 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0xd1, 0xcf, 0x6a, 0x84, 0x30,
	0x10, 0x06, 0x70, 0xb4, 0xd5, 0xd2, 0xa1, 0xbd, 0xa4, 0x56, 0x72, 0x2a, 0x25, 0xa7, 0x9e, 0x0a,
	0x9a, 0x27, 0x28, 0x85, 0x9e, 0x0a, 0x05, 0xbb, 0x2c, 0x7b, 0x55, 0x76, 0x60, 0x05, 0x35, 0xd9,
	0x24, 0xb2, 0x6f, 0xb3, 0xcf, 0xba, 0x90, 0x3f, 0x1a, 0x8f, 0xdf, 0x8f, 0xe1, 0x73, 0xc6, 0xc0,
	0xf3, 0x0f, 0xe2, 0xb1, 0xd7, 0xf2, 0x53, 0x2a, 0x61, 0x04, 0x49, 0x65, 0xc7, 0x0e, 0x40, 0x3c,
	0xfe, 0x9b, 0xd6, 0x60, 0x83, 0x52, 0x28, 0x43, 0x18, 0x3c, 0xc5, 0x4a, 0x93, 0xf7, 0xe4, 0xe3,
	0xb1, 0xd9, 0x18, 0x79, 0x03, 0xf8, 0x1a, 0x5a, 0x35, 0xba, 0x89, 0xd4, 0x4e, 0x44, 0xc2, 0xae,
	0xc9, 0x5a, 0x7d, 0x12, 0x97, 0x06, 0xcf, 0x33, 0x6a, 0x43, 0x0a, 0xc8, 0x7e, 0xfb, 0x09, 0x2b,
	0xdf, 0xe9, 0x42, 0xd0, 0xda, 0xf7, 0xb8, 0x10, 0x94, 0xd3, 0xbb, 0x55, 0x39, 0x29, 0x21, 0xff,
	0x16, 0x83, 0x50, 0x15, 0xbd, 0xb7, 0xec, 0xd3, 0xe2, 0x35, 0xcd, 0x22, 0xaf, 0x17, 0xe7, 0x34,
	0x8f, 0x9c, 0xb3, 0x57, 0x78, 0xd9, 0xec, 0xa7, 0xa5, 0x98, 0x34, 0xb2, 0xbf, 0x85, 0xed, 0x31,
	0x61, 0xef, 0x70, 0xee, 0xbe, 0x1d, 0xe6, 0xf0, 0x43, 0x22, 0x21, 0x14, 0x1e, 0x6c, 0xda, 0x8d,
	0xfe, 0x86, 0x10, 0x59, 0x09, 0xc5, 0xb6, 0xd0, 0x7d, 0xa8, 0xcb, 0xed, 0x2b, 0xf0, 0x5b, 0x00,
	0x00, 0x00, 0xff, 0xff, 0xea, 0x0f, 0xd8, 0xc1, 0x96, 0x01, 0x00, 0x00,
}
