// Code generated by protoc-gen-go. DO NOT EDIT.
// source: Printer.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//状态
type PrinterStateReport struct {
	UpState              string   `protobuf:"bytes,1,opt,name=UpState,proto3" json:"UpState,omitempty"`
	DnState              string   `protobuf:"bytes,2,opt,name=DnState,proto3" json:"DnState,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PrinterStateReport) Reset()         { *m = PrinterStateReport{} }
func (m *PrinterStateReport) String() string { return proto.CompactTextString(m) }
func (*PrinterStateReport) ProtoMessage()    {}
func (*PrinterStateReport) Descriptor() ([]byte, []int) {
	return fileDescriptor_f395917e02a3f846, []int{0}
}

func (m *PrinterStateReport) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PrinterStateReport.Unmarshal(m, b)
}
func (m *PrinterStateReport) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PrinterStateReport.Marshal(b, m, deterministic)
}
func (m *PrinterStateReport) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PrinterStateReport.Merge(m, src)
}
func (m *PrinterStateReport) XXX_Size() int {
	return xxx_messageInfo_PrinterStateReport.Size(m)
}
func (m *PrinterStateReport) XXX_DiscardUnknown() {
	xxx_messageInfo_PrinterStateReport.DiscardUnknown(m)
}

var xxx_messageInfo_PrinterStateReport proto.InternalMessageInfo

func (m *PrinterStateReport) GetUpState() string {
	if m != nil {
		return m.UpState
	}
	return ""
}

func (m *PrinterStateReport) GetDnState() string {
	if m != nil {
		return m.DnState
	}
	return ""
}

//出票
type PrinterContent struct {
	Aligyntype           string   `protobuf:"bytes,1,opt,name=Aligyntype,proto3" json:"Aligyntype,omitempty"`
	Fontsize             string   `protobuf:"bytes,2,opt,name=Fontsize,proto3" json:"Fontsize,omitempty"`
	Content              string   `protobuf:"bytes,3,opt,name=Content,proto3" json:"Content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PrinterContent) Reset()         { *m = PrinterContent{} }
func (m *PrinterContent) String() string { return proto.CompactTextString(m) }
func (*PrinterContent) ProtoMessage()    {}
func (*PrinterContent) Descriptor() ([]byte, []int) {
	return fileDescriptor_f395917e02a3f846, []int{1}
}

func (m *PrinterContent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PrinterContent.Unmarshal(m, b)
}
func (m *PrinterContent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PrinterContent.Marshal(b, m, deterministic)
}
func (m *PrinterContent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PrinterContent.Merge(m, src)
}
func (m *PrinterContent) XXX_Size() int {
	return xxx_messageInfo_PrinterContent.Size(m)
}
func (m *PrinterContent) XXX_DiscardUnknown() {
	xxx_messageInfo_PrinterContent.DiscardUnknown(m)
}

var xxx_messageInfo_PrinterContent proto.InternalMessageInfo

func (m *PrinterContent) GetAligyntype() string {
	if m != nil {
		return m.Aligyntype
	}
	return ""
}

func (m *PrinterContent) GetFontsize() string {
	if m != nil {
		return m.Fontsize
	}
	return ""
}

func (m *PrinterContent) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

type PrinterTicketRequest struct {
	WorkStation          string            `protobuf:"bytes,1,opt,name=WorkStation,proto3" json:"WorkStation,omitempty"`
	LineNums             string            `protobuf:"bytes,2,opt,name=LineNums,proto3" json:"LineNums,omitempty"`
	PrintRsds            []*PrinterContent `protobuf:"bytes,3,rep,name=PrintRsds,proto3" json:"PrintRsds,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *PrinterTicketRequest) Reset()         { *m = PrinterTicketRequest{} }
func (m *PrinterTicketRequest) String() string { return proto.CompactTextString(m) }
func (*PrinterTicketRequest) ProtoMessage()    {}
func (*PrinterTicketRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f395917e02a3f846, []int{2}
}

func (m *PrinterTicketRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PrinterTicketRequest.Unmarshal(m, b)
}
func (m *PrinterTicketRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PrinterTicketRequest.Marshal(b, m, deterministic)
}
func (m *PrinterTicketRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PrinterTicketRequest.Merge(m, src)
}
func (m *PrinterTicketRequest) XXX_Size() int {
	return xxx_messageInfo_PrinterTicketRequest.Size(m)
}
func (m *PrinterTicketRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PrinterTicketRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PrinterTicketRequest proto.InternalMessageInfo

func (m *PrinterTicketRequest) GetWorkStation() string {
	if m != nil {
		return m.WorkStation
	}
	return ""
}

func (m *PrinterTicketRequest) GetLineNums() string {
	if m != nil {
		return m.LineNums
	}
	return ""
}

func (m *PrinterTicketRequest) GetPrintRsds() []*PrinterContent {
	if m != nil {
		return m.PrintRsds
	}
	return nil
}

type PrinterTicketResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PrinterTicketResponse) Reset()         { *m = PrinterTicketResponse{} }
func (m *PrinterTicketResponse) String() string { return proto.CompactTextString(m) }
func (*PrinterTicketResponse) ProtoMessage()    {}
func (*PrinterTicketResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f395917e02a3f846, []int{3}
}

func (m *PrinterTicketResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PrinterTicketResponse.Unmarshal(m, b)
}
func (m *PrinterTicketResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PrinterTicketResponse.Marshal(b, m, deterministic)
}
func (m *PrinterTicketResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PrinterTicketResponse.Merge(m, src)
}
func (m *PrinterTicketResponse) XXX_Size() int {
	return xxx_messageInfo_PrinterTicketResponse.Size(m)
}
func (m *PrinterTicketResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PrinterTicketResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PrinterTicketResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*PrinterStateReport)(nil), "pb.PrinterStateReport")
	proto.RegisterType((*PrinterContent)(nil), "pb.PrinterContent")
	proto.RegisterType((*PrinterTicketRequest)(nil), "pb.PrinterTicketRequest")
	proto.RegisterType((*PrinterTicketResponse)(nil), "pb.PrinterTicketResponse")
}

func init() { proto.RegisterFile("Printer.proto", fileDescriptor_f395917e02a3f846) }

var fileDescriptor_f395917e02a3f846 = []byte{
	// 234 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x90, 0xc1, 0x4a, 0xc4, 0x30,
	0x10, 0x86, 0xe9, 0x16, 0xd4, 0x9d, 0x45, 0x0f, 0x83, 0x62, 0xf1, 0x20, 0x25, 0xa7, 0x3d, 0x15,
	0xd1, 0x27, 0x10, 0x45, 0x3c, 0x88, 0x48, 0x54, 0x3c, 0x5b, 0x1d, 0x25, 0xac, 0xce, 0xc4, 0x64,
	0xf6, 0xb0, 0x3e, 0x80, 0xcf, 0x2d, 0x69, 0x13, 0x5d, 0x3d, 0xfe, 0xff, 0x5f, 0xbe, 0x6f, 0x1a,
	0xd8, 0xbe, 0x09, 0x8e, 0x95, 0x42, 0xe7, 0x83, 0xa8, 0xe0, 0xc4, 0xf7, 0xe6, 0x12, 0x30, 0x97,
	0xb7, 0xfa, 0xa8, 0x64, 0xc9, 0x4b, 0x50, 0x6c, 0x60, 0xf3, 0xde, 0x0f, 0x45, 0x53, 0xb5, 0xd5,
	0x7c, 0x6a, 0x4b, 0x4c, 0xcb, 0x39, 0x8f, 0xcb, 0x64, 0x5c, 0x72, 0x34, 0x2f, 0xb0, 0x93, 0x49,
	0x67, 0xc2, 0x4a, 0xac, 0x78, 0x08, 0x70, 0xfa, 0xe6, 0x5e, 0x57, 0xac, 0x2b, 0x5f, 0x40, 0x6b,
	0x0d, 0x1e, 0xc0, 0xd6, 0x85, 0xb0, 0x46, 0xf7, 0x59, 0x60, 0x3f, 0x39, 0x79, 0x32, 0xa6, 0xa9,
	0x47, 0x4f, 0x8e, 0xe6, 0xab, 0x82, 0xdd, 0x2c, 0xba, 0x73, 0x4f, 0x0b, 0x52, 0x4b, 0x1f, 0x4b,
	0x8a, 0x8a, 0x2d, 0xcc, 0x1e, 0x24, 0x2c, 0xd2, 0x35, 0x4e, 0x38, 0xfb, 0xd6, 0xab, 0x24, 0xbc,
	0x72, 0x4c, 0xd7, 0xcb, 0xf7, 0x58, 0x84, 0x25, 0xe3, 0x11, 0x4c, 0x07, 0xaa, 0x8d, 0xcf, 0xb1,
	0xa9, 0xdb, 0x7a, 0x3e, 0x3b, 0xc6, 0xce, 0xf7, 0xdd, 0xdf, 0x7f, 0xb2, 0xbf, 0x1f, 0x99, 0x7d,
	0xd8, 0xfb, 0x77, 0x47, 0xf4, 0xc2, 0x91, 0xfa, 0x8d, 0xe1, 0x79, 0x4f, 0xbe, 0x03, 0x00, 0x00,
	0xff, 0xff, 0x44, 0x42, 0xe4, 0xa1, 0x6f, 0x01, 0x00, 0x00,
}
