// Code generated by protoc-gen-go. DO NOT EDIT.
// source: Reader.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//根据不同的类型，解析不同的数据结构
type ReaderDataRequest struct {
	Msg                  string   `protobuf:"bytes,1,opt,name=Msg,proto3" json:"Msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReaderDataRequest) Reset()         { *m = ReaderDataRequest{} }
func (m *ReaderDataRequest) String() string { return proto.CompactTextString(m) }
func (*ReaderDataRequest) ProtoMessage()    {}
func (*ReaderDataRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e7d61d47385a217b, []int{0}
}

func (m *ReaderDataRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReaderDataRequest.Unmarshal(m, b)
}
func (m *ReaderDataRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReaderDataRequest.Marshal(b, m, deterministic)
}
func (m *ReaderDataRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReaderDataRequest.Merge(m, src)
}
func (m *ReaderDataRequest) XXX_Size() int {
	return xxx_messageInfo_ReaderDataRequest.Size(m)
}
func (m *ReaderDataRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReaderDataRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReaderDataRequest proto.InternalMessageInfo

func (m *ReaderDataRequest) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type ReaderDataResponse struct {
	Msg                  string   `protobuf:"bytes,1,opt,name=Msg,proto3" json:"Msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReaderDataResponse) Reset()         { *m = ReaderDataResponse{} }
func (m *ReaderDataResponse) String() string { return proto.CompactTextString(m) }
func (*ReaderDataResponse) ProtoMessage()    {}
func (*ReaderDataResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e7d61d47385a217b, []int{1}
}

func (m *ReaderDataResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReaderDataResponse.Unmarshal(m, b)
}
func (m *ReaderDataResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReaderDataResponse.Marshal(b, m, deterministic)
}
func (m *ReaderDataResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReaderDataResponse.Merge(m, src)
}
func (m *ReaderDataResponse) XXX_Size() int {
	return xxx_messageInfo_ReaderDataResponse.Size(m)
}
func (m *ReaderDataResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ReaderDataResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ReaderDataResponse proto.InternalMessageInfo

func (m *ReaderDataResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func init() {
	proto.RegisterType((*ReaderDataRequest)(nil), "pb.ReaderDataRequest")
	proto.RegisterType((*ReaderDataResponse)(nil), "pb.ReaderDataResponse")
}

func init() { proto.RegisterFile("Reader.proto", fileDescriptor_e7d61d47385a217b) }

var fileDescriptor_e7d61d47385a217b = []byte{
	// 94 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x09, 0x4a, 0x4d, 0x4c,
	0x49, 0x2d, 0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2a, 0x48, 0x52, 0x52, 0xe5, 0x12,
	0x84, 0x88, 0xb9, 0x24, 0x96, 0x24, 0x06, 0xa5, 0x16, 0x96, 0xa6, 0x16, 0x97, 0x08, 0x09, 0x70,
	0x31, 0xfb, 0x16, 0xa7, 0x4b, 0x30, 0x2a, 0x30, 0x6a, 0x70, 0x06, 0x81, 0x98, 0x4a, 0x6a, 0x5c,
	0x42, 0xc8, 0xca, 0x8a, 0x0b, 0xf2, 0xf3, 0x8a, 0x53, 0x31, 0xd5, 0x25, 0xb1, 0x81, 0x4d, 0x36,
	0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0x02, 0xac, 0x28, 0xa1, 0x69, 0x00, 0x00, 0x00,
}
