// Code generated by protoc-gen-go. DO NOT EDIT.
// source: Scan.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//状态
type ScanStateReport struct {
	UpState              string   `protobuf:"bytes,1,opt,name=UpState,proto3" json:"UpState,omitempty"`
	DnState              string   `protobuf:"bytes,2,opt,name=DnState,proto3" json:"DnState,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ScanStateReport) Reset()         { *m = ScanStateReport{} }
func (m *ScanStateReport) String() string { return proto.CompactTextString(m) }
func (*ScanStateReport) ProtoMessage()    {}
func (*ScanStateReport) Descriptor() ([]byte, []int) {
	return fileDescriptor_aef344b222d3bf77, []int{0}
}

func (m *ScanStateReport) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ScanStateReport.Unmarshal(m, b)
}
func (m *ScanStateReport) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ScanStateReport.Marshal(b, m, deterministic)
}
func (m *ScanStateReport) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ScanStateReport.Merge(m, src)
}
func (m *ScanStateReport) XXX_Size() int {
	return xxx_messageInfo_ScanStateReport.Size(m)
}
func (m *ScanStateReport) XXX_DiscardUnknown() {
	xxx_messageInfo_ScanStateReport.DiscardUnknown(m)
}

var xxx_messageInfo_ScanStateReport proto.InternalMessageInfo

func (m *ScanStateReport) GetUpState() string {
	if m != nil {
		return m.UpState
	}
	return ""
}

func (m *ScanStateReport) GetDnState() string {
	if m != nil {
		return m.DnState
	}
	return ""
}

//开启扫码
type OpenScanRequest struct {
	WorkStation string `protobuf:"bytes,1,opt,name=WorkStation,proto3" json:"WorkStation,omitempty"`
	//间隔打开扫码时长
	ScanSpanTm           string   `protobuf:"bytes,2,opt,name=ScanSpanTm,proto3" json:"ScanSpanTm,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OpenScanRequest) Reset()         { *m = OpenScanRequest{} }
func (m *OpenScanRequest) String() string { return proto.CompactTextString(m) }
func (*OpenScanRequest) ProtoMessage()    {}
func (*OpenScanRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_aef344b222d3bf77, []int{1}
}

func (m *OpenScanRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OpenScanRequest.Unmarshal(m, b)
}
func (m *OpenScanRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OpenScanRequest.Marshal(b, m, deterministic)
}
func (m *OpenScanRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OpenScanRequest.Merge(m, src)
}
func (m *OpenScanRequest) XXX_Size() int {
	return xxx_messageInfo_OpenScanRequest.Size(m)
}
func (m *OpenScanRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_OpenScanRequest.DiscardUnknown(m)
}

var xxx_messageInfo_OpenScanRequest proto.InternalMessageInfo

func (m *OpenScanRequest) GetWorkStation() string {
	if m != nil {
		return m.WorkStation
	}
	return ""
}

func (m *OpenScanRequest) GetScanSpanTm() string {
	if m != nil {
		return m.ScanSpanTm
	}
	return ""
}

type OpenScanResponse struct {
	Scanbar              string   `protobuf:"bytes,1,opt,name=Scanbar,proto3" json:"Scanbar,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OpenScanResponse) Reset()         { *m = OpenScanResponse{} }
func (m *OpenScanResponse) String() string { return proto.CompactTextString(m) }
func (*OpenScanResponse) ProtoMessage()    {}
func (*OpenScanResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_aef344b222d3bf77, []int{2}
}

func (m *OpenScanResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OpenScanResponse.Unmarshal(m, b)
}
func (m *OpenScanResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OpenScanResponse.Marshal(b, m, deterministic)
}
func (m *OpenScanResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OpenScanResponse.Merge(m, src)
}
func (m *OpenScanResponse) XXX_Size() int {
	return xxx_messageInfo_OpenScanResponse.Size(m)
}
func (m *OpenScanResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_OpenScanResponse.DiscardUnknown(m)
}

var xxx_messageInfo_OpenScanResponse proto.InternalMessageInfo

func (m *OpenScanResponse) GetScanbar() string {
	if m != nil {
		return m.Scanbar
	}
	return ""
}

//关闭扫码
type CloseScanRequest struct {
	WorkStation          string   `protobuf:"bytes,1,opt,name=WorkStation,proto3" json:"WorkStation,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CloseScanRequest) Reset()         { *m = CloseScanRequest{} }
func (m *CloseScanRequest) String() string { return proto.CompactTextString(m) }
func (*CloseScanRequest) ProtoMessage()    {}
func (*CloseScanRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_aef344b222d3bf77, []int{3}
}

func (m *CloseScanRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CloseScanRequest.Unmarshal(m, b)
}
func (m *CloseScanRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CloseScanRequest.Marshal(b, m, deterministic)
}
func (m *CloseScanRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CloseScanRequest.Merge(m, src)
}
func (m *CloseScanRequest) XXX_Size() int {
	return xxx_messageInfo_CloseScanRequest.Size(m)
}
func (m *CloseScanRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CloseScanRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CloseScanRequest proto.InternalMessageInfo

func (m *CloseScanRequest) GetWorkStation() string {
	if m != nil {
		return m.WorkStation
	}
	return ""
}

type CloseScanResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CloseScanResponse) Reset()         { *m = CloseScanResponse{} }
func (m *CloseScanResponse) String() string { return proto.CompactTextString(m) }
func (*CloseScanResponse) ProtoMessage()    {}
func (*CloseScanResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_aef344b222d3bf77, []int{4}
}

func (m *CloseScanResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CloseScanResponse.Unmarshal(m, b)
}
func (m *CloseScanResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CloseScanResponse.Marshal(b, m, deterministic)
}
func (m *CloseScanResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CloseScanResponse.Merge(m, src)
}
func (m *CloseScanResponse) XXX_Size() int {
	return xxx_messageInfo_CloseScanResponse.Size(m)
}
func (m *CloseScanResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CloseScanResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CloseScanResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*ScanStateReport)(nil), "pb.ScanStateReport")
	proto.RegisterType((*OpenScanRequest)(nil), "pb.OpenScanRequest")
	proto.RegisterType((*OpenScanResponse)(nil), "pb.OpenScanResponse")
	proto.RegisterType((*CloseScanRequest)(nil), "pb.CloseScanRequest")
	proto.RegisterType((*CloseScanResponse)(nil), "pb.CloseScanResponse")
}

func init() { proto.RegisterFile("Scan.proto", fileDescriptor_aef344b222d3bf77) }

var fileDescriptor_aef344b222d3bf77 = []byte{
	// 180 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x0a, 0x4e, 0x4e, 0xcc,
	0xd3, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2a, 0x48, 0x52, 0x72, 0xe5, 0xe2, 0x07, 0x89,
	0x04, 0x97, 0x24, 0x96, 0xa4, 0x06, 0xa5, 0x16, 0xe4, 0x17, 0x95, 0x08, 0x49, 0x70, 0xb1, 0x87,
	0x16, 0x80, 0x05, 0x24, 0x18, 0x15, 0x18, 0x35, 0x38, 0x83, 0x60, 0x5c, 0x90, 0x8c, 0x0b, 0x44,
	0xa9, 0x04, 0x13, 0x44, 0x06, 0xca, 0x55, 0x0a, 0xe6, 0xe2, 0xf7, 0x2f, 0x48, 0xcd, 0x03, 0x19,
	0x15, 0x94, 0x5a, 0x58, 0x9a, 0x5a, 0x5c, 0x22, 0xa4, 0xc0, 0xc5, 0x1d, 0x9e, 0x5f, 0x94, 0x0d,
	0x92, 0xcf, 0xcc, 0xcf, 0x83, 0x1a, 0x85, 0x2c, 0x24, 0x24, 0x07, 0x71, 0x4d, 0x70, 0x41, 0x62,
	0x5e, 0x48, 0x2e, 0xd4, 0x44, 0x24, 0x11, 0x25, 0x1d, 0x2e, 0x01, 0x84, 0xa1, 0xc5, 0x05, 0xf9,
	0x79, 0xc5, 0x60, 0x27, 0x80, 0xf8, 0x49, 0x89, 0x45, 0x30, 0xc7, 0x41, 0xb9, 0x4a, 0x26, 0x5c,
	0x02, 0xce, 0x39, 0xf9, 0xc5, 0xa9, 0x24, 0xb9, 0x41, 0x49, 0x98, 0x4b, 0x10, 0x49, 0x17, 0xc4,
	0x92, 0x24, 0x36, 0x70, 0xf8, 0x18, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0x95, 0x20, 0x5c, 0x2f,
	0x2d, 0x01, 0x00, 0x00,
}
